### ISSUE TITLE
grad of anp.abs and anp.absolute returning NaN when input is zero

### ISSUE THREAD

**Issue by SpinOneThird** [HIPS/autograd#100]
anp.abs and anp.absolute return NaN when one of the inputs is identically zero:
`>> grad(anp.abs)(0.0)`

Note that anp.fabs does not have this issue.

The reason is the division by ans in the definition of the abs grad:
anp.abs.defgrad(     lambda ans, x : lambda g : g * anp.conj(x) / ans)

https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_grads.py#L96

I'm not sure what is the best way to fix this, as naive solutions involve assigning to an array which would break when taking higher order derivatives.

**Comment by mattjj** [comment]
Thanks for finding this!

I added some calls to `np.where` to avoid the division by zero, which arose from using the formula `g * np.conj(x) / np.abs(x)` for the reverse-mode Jacobian operator of the complex modulus function. This fix implements the definition that the derivative of the complex modulus function `lambda x: np.sqrt(x * np.conj(x))`, also known as `np.abs`, at zero is zero, which [seems to be the right definition at zero](https://math.stackexchange.com/questions/413405/derivative-of-absolute-value-over-the-complex-numbers). (Actually, I'm not sure where the formula  `g * np.conj(x) / np.abs(x)` came from, since I don't think `np.abs` is complex differentiable anywhere except zero, but I trust it was put there for a reason and I didn't change it.) The `np.fabs` function doesn't take complex arguments and so it just uses `g * np.sign(g)`, as you probably noticed.
