### ISSUE TITLE
Make an object oriented version of grad

### ISSUE THREAD

**Issue by entron** [HIPS/autograd#108]
I am new to autograd, and I like the idea of the project very much! 
I am wondering whether it is possible to make an object oriented version of grad. That is instead of 

```
def grad(fun, argnum=0):
```

one defines a new function like

```
def grad(class, class_fun, class_property):
```
to compute the gradient of `class_fun` with respect to `class_property`.

In this way (or maybe other ways) I don't have to rewrite existing class into a function form.

**Comment by mattjj** [comment]
You can already call `grad` on class methods; just write `grad(class.class_fun)` or `grad(class.class_fun)(class.class_property)`. Just pass in `argnum` corresponding to the argument number of `class.class_fun` with respect to which you want to differentiate. Issue #67 has an example.

**Comment by entron** [comment]
Thanks for the quick response! Here is an example:

```
class A(object):
    def __init__(self):
        self.W = np.random.rand(size=(10, 10))

    def output(self, x):
        return np.dot(self.W, x)
```

I want to compute the gradient of `output` with respect to `self.W`. However as `self.W` is not an argument of `output`, so I can't tell grad this using argnum. Therefore, my question is is there a way to compute the gradient without rewriting the class?

**Comment by mattjj** [comment]
I think you'd have to rewrite it. Autograd works on functions by boxing arguments before they get passed in. Here, the argument you care about boxing isn't actually an argument of `output`, but rather it's an argument of `np.dot`. So in this simple example, it's really the gradient of `np.dot` that you want, with respect to its first argument, rather than any gradient of `output`.

You might be able to reorganize your code so that inside a class method you call a pure function with arguments that are class members, like this:

```python
class A(object):
    def __init__(self):
        self.W = np.random.rand(size=(10,10))

    def output(self, x):
        return self._output(self.W, x)
```

Then you can call `grad` on the `_output` method to get its gradient with respect to argument 0.

**Comment by entron** [comment]
Indeed, with this method I can already reuse most of the existing code. Thanks a lot!
