### ISSUE TITLE
Adding a grad for np.take

### ISSUE THREAD

**Issue by ericmjl** [HIPS/autograd#109]
There is a function [`np.take`](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.take.html), for which I think the definition of the gradient is zero, because it behaves like `np.oneslike`, `np.iscomplex` etc., in that there's no mathematical operation, but simply a rearrangement of data. Would this be correct?

I'm asking because I am using the function, and want to see if I can add this function to `autograd.numpy`, and put in a PR...?

**Comment by mattjj** [comment]
The gradient shouldn't be zero; it should act like indexing, as in

```python
grad(lambda x: np.take(x, 1)**2)(np.arange(2))
```

should behave like

```python
grad(lambda x: x[1]**2)(np.arange(2))
```

However, I'm surprised that it's not already wrapped. We use [a version of take and its gradient](https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_extra.py#L9-L14) internally. My guess is either `untake` needs some extra embellishments to support all the functionality of `np.take`, or failing to define the gradient of `np.take` was just an oversight.

**Comment by davidweichiang** [comment]
The internal take is different from np.take, though.

**Comment by jermwatt** [comment]
@ericmjl instead of defining the gradient for `np.take` I used 'fancy indexing' to get the same result (which `autograd` already knows how to differentiate).

Say I want to take the `index` set from an array `A` using `np.take`, giving `A_index`

`
A_index = np.take(A,index)
`

You can also do this using fancy indexing as follows (seems just as fast)

`
A_index = A.flatten()[index]
`

and `autograd` can compute gradients on this version already.

**Comment by ericmjl** [comment]
Thanks @jermwatt!
