### ISSUE TITLE
Bug when using powers?

### ISSUE THREAD

**Issue by jcockayne** [HIPS/autograd#116]
Hi guys,

I'm seeing a strange error when I use `x**2` vs. `x*x` in a function I'm differentiating with autograd. I'm on v1.1.4. Reproducing code is below:

```python
def fun(x):
    return np.exp(-(x*x))
d1 = autograd.grad(fun)
d2 = autograd.grad(d1)
d3 = autograd.grad(d2)
d4 = autograd.grad(d3)
# prints -0.0, -2.0, 0.0, 12.0
print d1(0.), d2(0.), d3(0.), d4(0.)

def fun(x):
    return np.exp(-(x**2))
d1 = autograd.grad(fun)
d2 = autograd.grad(d1)
d3 = autograd.grad(d2)
d4 = autograd.grad(d3)
# prints -0.0, -2.0, nan, nan
print d1(0.), d2(0.), d3(0.), d4(0.)
```

Any idea why this could be happening?

Cheers!
Jon

**Comment by mattjj** [comment]
Good catch. I think it's because the formula used the call to `anp.power.defgrad` [is not valid at zero](https://en.wikipedia.org/wiki/Differentiation_rules#The_polynomial_or_elementary_power_rule), but I am afk and can't check right now. If that's the case then the fix would be to test if `y` is 0.
