### ISSUE TITLE
pip version out of date

### ISSUE THREAD

**Issue by robwell** [HIPS/autograd#120]
I was trying some of the samples and some of the functions from util.py are missing from the pip install. There are no notes on building from the github so I'm wondering what is the best way to proceed. This is very cool stuff!

**Comment by robwell** [comment]
I solved my problem. In case this is useful to others:
1) Download the github sources (I downloaded a zip as opposed to using git)
2) If you installed with pip then run pip uninstall autograd
3) In the autogrid-master directory run python ./setup.py build followed by python ./setup.py install

You should be all set.

**Comment by mattjj** [comment]
You can also do this:

```
git clone https://github.com/hips/autograd.git
cd autograd
pip install -e .
```

That's a standard pip way to install a package as "editable", so that pip can manage it (it symlinks the autograd repo directory into site-packages) yet you can edit the code or update it with git pulls. 

We'll update the pypi version when we get the chance. Thanks for letting us know!

**Comment by robwell** [comment]
Thank you, that is a much easier way!

**Comment by mattjj** [comment]
I just pushed the current github master to pypi.
