### ISSUE TITLE
Differentiating chart based dynamic programming algorithms

### ISSUE THREAD

**Issue by se4u** [HIPS/autograd#13]
Consider the following code, it sums up the entries in y by keeping a running sum in the chart at `x[0, 0]` and finally outputs the value at chart position `x[0, 0]` when the loop finishes. This is a /mwe/ and more complicated logic is used in algorithms like inside-outside for CKY parsing or forward-backward for finding the sum of all valid paths in a linear chain CRF. I was wondering if it was possible to fix the library to get gradients for such chart based algorithms ? 
```python
import autograd.numpy as np
from autograd import grad
def assignment(y, x):
    for i in range(3):
        x[0, 0] = np.sum(np.array([y[i], x[0, 0]]))
    return x[0, 0]

def test_assignment():
    x = np.zeros((1,1))
    f = lambda y : assignment(y, x)
    y = np.random.rand(3,)
    print f(y)
    print grad(f)(y)
    return

if __name__ == "__main__":
    test_assignment()

>>> 0.530750805709
Traceback (most recent call last):
  File "test_autograd.py", line 35, in <module>
    test_assignment()
  File "test_autograd.py", line 31, in test_assignment
    print grad(f)(y)
  File "~/site-packages/autograd/core.py", line 16, in gradfun
    end_node = fun(*args, **kwargs)
  File "test_autograd.py", line 28, in <lambda>
    f = lambda y : assignment(y, x)
  File "test_autograd.py", line 23, in assignment
    x[0, 0] = np.max(np.array([y[i], x[0, 0]]))
TypeError: float() argument must be a string or a number
```

**Comment by se4u** [comment]
Oops, it seems that this issue itself can simply be circumvented by storing the chart in a dictionary instead of as a numpy array. So this issue can be closed or removed.

**Comment by se4u** [comment]
There is a separate issue however related to this same problem where the gradient is correct the first time and wrong the second time. See the gist at for a mwe
https://gist.github.com/cdad977652d05e5d2219

**Comment by mattjj** [comment]
Array assignment is a [planned feature](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md#planned-features), so hopefully we can eventually close this issue when array assignment works!

**Comment by mattjj** [comment]
With regards to your [most recent comment](https://github.com/HIPS/autograd/issues/13#issuecomment-92572351), the test you linked throws an error on the current master, and it should because [in the loop body](https://gist.github.com/se4u/cdad977652d05e5d2219#file-test_autograd-py-L14) there's a call to `np.array` which creates an object array (it evaluates to something like `np.array([[1.], 2]])`). If y is made to be 1-dimensional with a line like `y = np.random.rand(3)` instead of being [2 dimensional](https://gist.github.com/se4u/cdad977652d05e5d2219#file-test_autograd-py-L20), running against current master the test doesn't print 'fail' and works all three times.

Since that test file was fixed at some point, I'm going to close this issue.
