### ISSUE TITLE
what does flatten_func mean？

### ISSUE THREAD

**Issue by guotong1988** [HIPS/autograd#133]
I ' m reading the code in https://github.com/HIPS/autograd/blob/master/examples/optimizers.py#L19
and please tell me the meaning of function flatten_func 
https://github.com/HIPS/autograd/blob/master/autograd/util.py#L190
Thank you very much!

**Comment by mattjj** [comment]
It turns function that takes some structured argument, like a dict or nested tuple, into a new version of that function that instead takes a numpy vector as its argument. It's useful for 'canonicalizing' a function to operate on vectors. We use it in some optimizers because it means vector arithmetic can be performed on the function arguments.

It might be easiest to look at a real example of [its usage in optimizers.py](https://github.com/HIPS/autograd/blob/master/examples/optimizers.py).

Please reopen if that's not clear!

**Comment by guotong1988** [comment]
Thank you! could you please tell me the meaning of [flattened_grad, unflatten, x]？Thank you again！ (https://github.com/HIPS/autograd/blob/master/examples/optimizers.py#L19)

**Comment by mattjj** [comment]
Here's a simple example:

```python
from autograd.util import flatten_func

def f(struct):
   ((a, b), c) = struct
   return a + b + c

x = ((1., 2.), 3.)
print f(x)

flat_f, unflatten, flat_x = flatten_func(f, x)
print flat_x
print unflatten(flat_x)
print flat_f(flat_x)
```
