### ISSUE TITLE
Divide by zero in np.power

### ISSUE THREAD

**Issue by j-wilson** [HIPS/autograd#149]
I've  been running into divide by zero issues when using `anp.power` with inputs equaling zero. This issue seems similar to #93. The [line](https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_grads.py#L77) in question seems to be:
```
anp.power.defgrad(lambda ans, x, y : unbroadcast(ans, x, lambda g :\
    g * y * x ** (anp.where(y, y - 1, 1.))))
```

If this is a bug, would the following modification suffice?
```
anp.power.defgrad(lambda ans, x, y : unbroadcast(ans, x, lambda g :\
    g * y * x ** (anp.where(anp.logical_and(y, x),  y - 1, 1.))))
```
If additional numerical stability is needed, `anp.logical_and(y, x)` could be swapped out for `anp.logical_and(y, anp.greater(anp.abs(x), const)` where `const` is some small positive constant, e.g., `10.0*anp.finfo(x.dtype).eps`.

**Comment by mattjj** [comment]
Wow, nice catch and nice code.

I ran these and only one gave a divide-by-zero error:

```python
print grad(np.power)(1., 0.)
print grad(np.power)(0., 1.)
print grad(np.power)(0., 0.)

print grad(np.power, 1)(1., 0.)
print grad(np.power, 1)(0., 1.)  # divide by zero error!
print grad(np.power, 1)(0., 0.)
```

Since the derivative is with respect to argument index 1, the line of code is actually [the next one](https://github.com/HIPS/autograd/blob/3336f549c5164a52d0c94654ea912920468055e2/autograd/numpy/numpy_grads.py#L78). The problem is that we're evaluating `x * anp.log(x)` when `x` is zero, so we get a divide-by-zero error in evaluating the log.

I think a good fix is to replace `anp.log(x)` with `anp.log(anp.where(x, x, 1.))`, though let me know if there's something more slick to do.

I'll push that fix plus a test that covers the issue. Please reopen if I missed things!
