### ISSUE TITLE
`from autograd.numpy import *` causes code to fail

### ISSUE THREAD

**Issue by yig** [HIPS/autograd#153]
Adding `from autograd.numpy import *` below `import autograd.numpy as np` causes the following code to fail (`AttributeError: 'float' object has no attribute 'exp'`). Adding it above doesn't cause any problems.

```
import autograd.numpy as np   # Thinly-wrapped version of Numpy

## Comment out the following line of code and everything works.
## Moving it above the `import autograd.numpy as np` also works.
from autograd.numpy import *

from autograd import grad

def f( x ):
    x = np.maximum( 1.5, x )
    print type(x)
    return np.sum( np.exp( 2*x ) )

grad_f = grad(f)
x = np.linspace(1,2,25).reshape(5,5)
# x = 1.0
print f(x)
print "Gradient of linspace(1,2) is", grad_f(x)
```

**Comment by mattjj** [comment]
Thanks for finding this.

The problem was that `from autograd.numpy import *` re-binds the name `np` to the unwrapped numpy (i.e. the underlying numpy rather than autograd's wrapper). Ultimately that's becausethe autograd/numpy/numpy_wrapper.py file uses the unwrapped numpy under the name `np`, and autograd/numpy/__init__.py does a `from .numpy_wrapper import *`.

To fix this importing issue, we can just prevent the line `from autograd.numpy import *` from clobbering the `np` name. One way to do that would be to define an `__all__` variable in autograd/numpy/__init__.py or autograd/numpy/numpy_wrapper.py which excludes the name `np`. However, we'd then have to generate a list of all the names we do want to include, which seems unnecessary.

Another solution, which I just pushed, is to use the name `_np` in numpy_wrapper.py. Names that start with underscores are excluded from imports of the form `from autograd.numpy import *` because Python convention is that they're private.
