### ISSUE TITLE
List take not compatible with slices

### ISSUE THREAD

**Issue by j-towns** [HIPS/autograd#169]
Since the recent revisions to the core, container types don't seem to be compatible with taking a slice (as opposed to just a single element). As a minimal example:
```python
>>> from autograd import grad
>>> def f(x):
...     s = slice(None, -1, None)
...     y = x[s]
...     return y[0]
... 
>>> grad(f)([1., 2., 3.])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamietownsend/autograd/autograd/convenience_wrappers.py", line 26, in gradfun
    return vjp(1.0)
  File "/Users/jamietownsend/autograd/autograd/core.py", line 18, in <lambda>
    return lambda g : backward_pass(g, end_node, start_node), end_node
  File "/Users/jamietownsend/autograd/autograd/core.py", line 37, in backward_pass
    cur_outgrad = vsum(node.vspace, *outgrads[node])
  File "/Users/jamietownsend/autograd/autograd/core.py", line 131, in vsum
    return primitive_vsum(vspace, *args)
  File "/Users/jamietownsend/autograd/autograd/core.py", line 70, in __call__
    result_value = self.fun(*argvals, **kwargs)
  File "/Users/jamietownsend/autograd/autograd/core.py", line 138, in primitive_vsum
    ans = arg.mut_add(ans)
  File "/Users/jamietownsend/autograd/autograd/container_types.py", line 30, in mut_add
    result[idx] = vs.shape[idx].mut_add(result[idx], x)
AttributeError: 'list' object has no attribute 'mut_add'
```
Anything where you take more than one list element in one go will break, e.g.
```python
>>> def f(x):
...     y = x[1:3]
...     return y[0]
... 
>>> grad(f)([1., 2., 3.])
```
This breaks the varational_autoencoder example (which is how I found the bug). In particular line 48:
```python
    for W, b in params[:-1]:
```
I can try to work out a fix for this but thought I would raise it in case one of you guys knows how to fix it real quick 😉.

**Comment by mattjj** [comment]
Wow, this is a big regression. Thanks for finding this.

It looks like instead of doing a mutating (in-place) add, for list types we used to [do some surgery on the list and replace the elements in question](https://github.com/HIPS/autograd/blob/0f026abd25a7c8fb182aaa46a04003b6cca35872/autograd/container_types.py#L87-L93). That strategy could probably work again.

**Comment by mattjj** [comment]
If we dispatch to `vs.mut_add` there, instead of `vs.shape[idx].mut_add`, it does the right thing.

**Comment by mattjj** [comment]
I just pushed to master an attempt at a fix. I say it's an attempt and not a complete fix because (1) I didn't do a good job writing tests and (2) there may be better implementations. I'm not sure if we can avoid this new call to `isinstance` that I added, or even if it's the right check, but at least it only happens once (rather than happening once for every time the object created by the indexing operation is used).

**Comment by mattjj** [comment]
@j-towns any thoughts on this implementation?

**Comment by dougalm** [comment]
Thanks for catching this @j-towns! Our container types are woefully undertested. I'll write some more comprehensive tests for arbitrary nesting, slicing and dicing. @mattjj, your commit missed indexing (or slicing rather) vs.shape so it fails if the the list elements have different types but otherwise it looks good.

**Comment by mattjj** [comment]
I swear I had `vs.shape[idx]` at some point, but I must have lost it when cleaning up the code for the commit!
