### ISSUE TITLE
<class 'autograd.core.FloatNode'> Autograd FloatNode with value 9.02807887854e-05 and 1 tape(s)

### ISSUE THREAD

**Issue by biosckon** [HIPS/autograd#190]
Hi Gents,  thank you for the brilliant library!

Have strange one for you... My function is very simple:
```python
def shf_Lambda(PC, A, Lambda, B, _):
	return A * pow(PC, -Lambda) + B
````

This works
```python
grad(shf_Lambda)(3.56086034178, 0.000297981983749, 0.557152330875, 0.08155670017, -9999.0)
``` 
but sometimes it tells me:
```python
Traceback (most recent call last):
  File "<string>", line 590 (797), in <module>
  File "<string>", line 580 (787), in run
  File "<string>", line 396 (603), in GenRPV
  File "<string>", line 360 (567), in slope
  File "C:\Apps\5Techlog\PythonScripts\External272_x64\autograd\core.py", line 22, in gradfun
    return backward_pass(*forward_pass(fun,args,kwargs,argnum))
  File "C:\Apps\5Techlog\PythonScripts\External272_x64\autograd\core.py", line 32, in forward_pass
    except Exception as e: add_extra_error_message(e)
  File "C:\Apps\5Techlog\PythonScripts\External272_x64\autograd\core.py", line 417, in add_extra_error_message
    raise_(etype, value, traceback)
  File "C:\Apps\5Techlog\PythonScripts\External272_x64\autograd\core.py", line 31, in forward_pass
    try: end_node = fun(*args, **kwargs)
  File "C:\Apps\0Projects\Iulian_SHF\SHF_2016.2\PythonScripts\IulianLIB.py", line 77 (91), in shf_Lambda
    return A * pow(PC, -Lambda) + B
TypeError: a float is required
```

What happens is first argument for some reason become of type:
```python
<class 'autograd.core.FloatNode'> Autograd FloatNode with value 9.02807887854e-05 and 1 tape(s)
```

Only first argument to the function becomes <class 'autograd.core.FloatNode'>! Rest of the args stay normal floats. Any hints towards a solution? 

Thank you!

**Comment by mattjj** [comment]
Glad you like the library!

Can you give a failing test case? It's hard to debug without knowing when it fails.

Here's a guess. Autograd works by operator overloading, and maybe the builtin `pow` isn't being overloaded properly (though I don't know why it would work sometimes, rather than always working or never working, but maybe it has something to do with higher-order differentiation). You could rewrite it with the binary operator `**`, as in

```python
def shf_Lambda(PC, A, Lambda, B, _):
	return A * PC**(-Lambda) + B
```

Even better, you could rewrite it to use numpy's `power` function, as in

```python
import autograd.numpy as np

def shf_Lambda(PC, A, Lambda, B, _):
    return A * np.power(PC, -Lambda) + B
```

Also, I can tell from the existence of `FloatNode` and the tapes that the autograd version you're using is older than the current master branch. We haven't updated the pypi (pip) version in a while, but maybe we should do that if this bug proves resilient.

**Comment by biosckon** [comment]
Rewriting in terms of Numpy fixed it. Thank you!

I'll close for now but will try to provide minimum reproducible and reopen if I can land on something concrete.

Thanks again!

**Comment by biosckon** [comment]
OK I have a minimum reproducible.
The culprit is ```from math import pow```

I'm working with a python embedded into our inhouse software, so when creating and importing my own libraries I must do "strange" things like the one above... Or simpler put "a short between a keyboard and the chair".

```python
from math import pow
import autograd.numpy as np
from autograd import grad

fn = (lambda PC, A, Lambda, B, _: A * pow(PC, -Lambda) + B)
dfn = grad(fn)

print fn(1.0, 1.0, 1.0, 1.0, 1.0)
print dfn(1.0, 1.0, 1.0, 1.0, 1.0)
```

**Comment by mattjj** [comment]
Thanks for the detailed yet concise report!

I think that confirms that the problem is that we don't wrap the standard math library. If we did wrap the math library, you could replace `from math import pow` with something like `from autograd.math import pow`, analogous to the numpy case.

Because we do override binary infix operators (like `**`) and we wrap `np.power`, the way to do this with autograd now is to use those instead of `math.pow`. However, for completeness maybe we could also offer `from autograd.math import pow`. (The math library isn't too big, and I think we could just copy the vjp definitions from the corresponding numpy ones.) Would that be advantageous for your use case?

In case you find this interesting, here's how we could wrap `math.pow` (warning: untested code!):

```python
from autograd.core import primitive
import math

pow = primitive(math.pow)
pow.defvjp(lambda g, ans, vs, gvs, x, y, *args:
           g * y * pow(x, y-1, *args), argnum=0)
pow.defvjp(lambda g, ans, vs, gvs, x, y, *args:
           g * log(x if x != 0 else 1.) * pow(x, y, *args), argnum=1)
pow.defvjp_is_zero(argnums=(2,))

log = primitive(math.log)
log.defvjp(lambda g, ans, vs, gvs, x: g / x)
```

However, assuming you don't rely on any bignum support (which might not interact well with autograd's floating point math anyway) or on the three-argument version of `pow`, and assuming you are willing to import numpy, it would be shorter just to write

```python
import autograd.numpy as np
pow = np.power
```

If wrapping the math library so as to provide things like `import autograd.math as math` is useful to you, we'd like to hear about it, and then we'd probably leave this issue or another one open so we can provide support for it. However, if that feature isn't actually important to you because you can just use infix operators or numpy, then I would lean towards closing the issue.

**Comment by biosckon** [comment]
Hey Matt I'd rather err on simpler solution and use numpy everywhere :) for my case.
Please mention in the tutorial that "math" not supported.
Closing as you guys did solve my specific issue 👍 
Thank you!
