### ISSUE TITLE
Trouble with higher order gradients wrt list arguments

### ISSUE THREAD

**Issue by med-int** [HIPS/autograd#198]
I'm working on a model which requires differentiating through a few iterations of SGD. Here's a working snippet that shows the idea: 

```python
import autograd.numpy as np
from autograd import grad 

def objective(y, x):
    return np.sum(np.dot(x, y))

def sgd(f, y, x):
    g = grad(f, argnum=1)
    for i in range(5):
        x = x - 0.1 * g(y, x)
    return f(y, x)

def wrapper(y):
    x = np.random.randn(1, 3)
    return np.sum(sgd(objective, y, x))

y = np.random.randn(3, 1)
print(" Forward works: " + str(wrapper(y)))
g = grad(wrapper)
print("Backward works: " + str(g(y)))
```

The example above shows that process works in the case is in which the arguments to the objective function are arrays. But I also need it to work when the arguments are lists, and this seems to fail, as the following slight modification of the code above demonstrates:

```python
import autograd.numpy as np
from autograd import grad 

def objective(y, x):
     return np.sum(np.dot(x[0], y) + x[1])

def sgd(f, y, x):
    g = grad(f, argnum=1)
    for i in range(5):
        for j in range(2):
	    x[j] = x[j] - 0.1 * g(y, x)[j]
    return f(y, x)

def wrapper(y):
    x = [np.random.randn(1, 3), np.random.randn(1)]
    return np.sum(sgd(objective, y, x))

y = np.random.randn(3, 1)
print("Forward works:  " + str(wrapper(y)))
g = grad(wrapper)
print("Backward works: " + str(g(y)))
```

Running this version gives the error:

```
File "/Applications/anaconda/lib/python2.7/site-packages/autograd/numpy/numpy_extra.py", line 90, in new_array_node
    raise TypeError("Can't differentiate wrt numpy arrays of dtype {0}".format(value.dtype))
TypeError: Can't differentiate wrt numpy arrays of dtype object
```

I thought the problem might have to do with the assignment in the the `sgd` function, as I know that assignments to arrays are not supported. But this is an assignment to a list, rather than array, something that seems to work in general.

Any advice? Thanks!

**Comment by mattjj** [comment]
Packing and unpacking container types (like lists) can get tricky because we can't intercept all the Python syntax for making lists (like literals and comprehensions), so lists sometimes contain instances of our Node classes and sometimes the lists themselves are Nodes. (Another issue is that we don't generally support mutating assignment into data structures, though it will work in the first case where you have things like lists of Nodes.)

I think the error here arises from differentiating with respect to a list that itself contains Nodes, but the outer `grad` call doesn't notice the Nodes inside the list (we don't descend recursively into data structures looking for Nodes), leading to getting a Node inside a Node and hence (eventually) an error.

We can fix the problem by making sure the relevant lists are Nodes, rather than native lists that contain Nodes. On the current master branch (not necessarily the pip version that I think you're using), you can use the function `make_list` to do that, which is in `autograd.container_types`. Basically, to be safe, you can call `make_list` wherever you might use Python list syntax, so `[a, b, c]` would become `make_list(a, b, c)`. (Most use cases Just Work™, so we don't advertise these functions very well, but higher order differentiation involving lists like this is one case where they may be necessary.)

I think this version of the code, which calls `make_list` and also avoids mutating assignment into lists, works on the current master branch:

```python
import autograd.numpy as np
from autograd import grad 
from autograd.container_types import make_list

def objective(y, x):
     return np.sum(np.dot(x[0], y) + x[1])

def sgd(f, y, x):
    g = grad(f, argnum=1)
    for i in range(5):
        x = make_list(*[x[j] - 0.1 * g(y, x)[j] for j in range(2)])
    return f(y, x)

def wrapper(y):
    x = [np.random.randn(1, 3), np.random.randn(1)]
    return np.sum(sgd(objective, y, x))

y = np.random.randn(3, 1)
print("Forward works:  " + str(wrapper(y)))
g = grad(wrapper)
print("Backward works: " + str(g(y)))
```

You might have to use the git master version for that code to work. We'll try to get the pip version updated soon.

**Comment by mattjj** [comment]
I just updated the pypi version (1.1.9), so you can try upgrading that way if necessary.

**Comment by mattjj** [comment]
I'm going to close this issue because I think using `make_list` solves it, but please reopen if you're still having trouble.

**Comment by med-int** [comment]
Thanks so much for your quick response! `make_list` does indeed work. I had one follow-up question: what's the right way to make something similar work for dictionaries, rather than lists? 

I tried (i) calling the ordinary constructor with `make_list` wrapping the arguments, and (ii) writing my own `make_dict`, but neither of these worked. (I know that `make_dict` should be easy - I guess I'm just missing something.) 

Below is some test code. Thanks again!

```python
import autograd.numpy as np
from autograd import grad 
from autograd.container_types import make_list
from autograd.core import primitive

def objective(y, x):
     return np.sum(np.dot(x["a"], y) + x["b"])

def sgd(f, y, x):
    g = grad(f, argnum=1)
    for i in range(5):
        grad_dict = g(y, x)
        for k in x.keys():
            x[k] = x[k] - 0.1 * grad_dict[k]
    return f(y, x)

def wrapper(y):
    x = {"a": np.random.randn(1, 3), "b": np.random.randn(1)}
    return np.sum(sgd(objective, y, x))

y = np.random.randn(3, 1)
print("Forward works:  " + str(wrapper(y)))
g = grad(wrapper)
print("Backward works: " + str(g(y)))
```

**Comment by mattjj** [comment]
Writing a `make_dict` is subtle because we might have to do two levels of unpacking to find Nodes: if we wanted to call our function like `make_dict([(key1, val1), (key2, val2)])`, then we need to handle the argument being a list of Nodes or a list of pairs of Nodes (or a mixture of the two). That is, each `(key, val)` pair may be a SequenceNode, or `key` and `val` may separately be nodes paired up in a Python tuple or list.

I think one solution is to have a non-primitive `make_dict` that first unpacks down to the level of individual `key`s and `val`s, so that we know which case we're in, and then have a primitive `_make_dict` that yields a DictNode. Here's one version, though it can probably be improved:

```python
def make_dict(pairs):
    keys, vals = zip(*pairs)
    return _make_dict(make_list(*keys), make_list(*vals))
@primitive
def _make_dict(keys, vals):
    return dict(zip(keys, vals))
_make_dict.defvjp(lambda g, ans, vs, gvs, keys, vals: [g[key] for key in keys],
                  argnum=1)
```

A DictNode won't like mutating assignment, so you'd want to replace lines like this:

```python
for k in x.keys():
    x[k] = x[k] - 0.1 * grad_dict[k]
```

with things like

```python
x = make_dict([(k, x[k] - 0.1 * grad_dict[k]) for k in x])  # untested!
```

**Comment by med-int** [comment]
Awesome - works great.
