### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by yccai** [HIPS/autograd#200]
When I run the following script, an error occurs: ImportError: No module named numpy. I do not know why.

`from __future__ import absolute_import
import autograd.numpy as np
import matplotlib.pyplot as plt
from autograd import elementwise_grad

def tanh(x):
    return (1.0 - np.exp(-x))  / (1.0 + np.exp(-x))

d_fun      = elementwise_grad(tanh)       # First derivative
dd_fun     = elementwise_grad(d_fun)      # Second derivative
ddd_fun    = elementwise_grad(dd_fun)     # Third derivative
dddd_fun   = elementwise_grad(ddd_fun)    # Fourth derivative
ddddd_fun  = elementwise_grad(dddd_fun)   # Fifth derivative
dddddd_fun = elementwise_grad(ddddd_fun)  # Sixth derivative

x = np.linspace(-7, 7, 200)
plt.plot(x, tanh(x),
         x, d_fun(x),
         x, dd_fun(x),
         x, ddd_fun(x),
         x, dddd_fun(x),
         x, ddddd_fun(x),
         x, dddddd_fun(x))

plt.axis('off')
plt.savefig("tanh.png")
plt.show()`

**Comment by dhirschfeld** [comment]
That means that numpy, which is a dependency of autograd, isn't installed in the Python you used to run that script.

**Comment by yccai** [comment]
Thanks for your answer. But if I execute this line "import autograd.numpy as np" in interact Window, no error happens.

**Comment by dhirschfeld** [comment]
What does it do if you try `import numpy as np`?

On 16 Mar 2017 5:49 pm, "yccai" <notifications@github.com> wrote:

Thanks for your answer. But if I execute this line "import autograd.numpy
as np" in interact Window, no error happens.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/HIPS/autograd/issues/200#issuecomment-286981818>, or mute
the thread

**Comment by yccai** [comment]
I try `import numpy as np` . It works

**Comment by j-towns** [comment]
It's possible you have multiple Python installs and one of them has numpy installed while the other does not. Please double check that numpy is installed for the version of Python with which you are running the script. Put
```python
import numpy as _np
```
at the top of a the script. If *that line* throws an input error, then numpy is not installed for the Python which is running the script.

**Comment by yccai** [comment]
@j-towns 
I try as what you say, an import error is thrown. It say that  ImportError: No module named numpy. But how can I solve it? Need I re-install numpy?

**Comment by mattjj** [comment]
I think as @j-towns suggests you probably have multiple Python systems installed, and you're running one interactively to test `import numpy as np` while executing the script with another, in which numpy can't be imported. You can either install numpy in the Python system that doesn't have it, or you can execute your script with the one that does. 

Because this isn't an autograd-specific issue, and is rather a Python setup and numpy installation issue, I'm going to close this.

**Comment by yccai** [comment]
@mattjj 
Thanks for your suggestion. I have a try.
