### ISSUE TITLE
value_and_multigrad

### ISSUE THREAD

**Issue by hbredin** [HIPS/autograd#218]
Is the code below the right way to write the (missing, afaict) `value_and_multigrad` function?

```python
def value_and_multigrad(fun, argnums=[0]):
    def combined_arg_fun(multi_arg, *args, **kwargs):
        extra_args_list = list(args)
        for argnum_ix, arg_ix in enumerate(argnums):
            extra_args_list[arg_ix] = multi_arg[argnum_ix]
        return fun(*extra_args_list, **kwargs)
    gradfun = value_and_grad(combined_arg_fun, argnum=0)
    def gradfun_rearranged(*args, **kwargs):
        multi_arg = tuple([args[i] for i in argnums])
        return gradfun(multi_arg, *args, **kwargs)
    return gradfun_rearranged
```

**Comment by mattjj** [comment]
That looks good to me, though since it shares a lot of code with `multigrad` it would be nice to write one in terms of the other (e.g. `multigrad` could be redefined in terms of `value_and_multigrad` and then just throw away the value). Want to write a test and then make a PR to add this to convenience_wrappers.py?

**Comment by hbredin** [comment]
Pull request #220 does just that and is now ready for review.
