### ISSUE TITLE
Question: Constructing a sparse matrix

### ISSUE THREAD

**Issue by eric-wieser** [HIPS/autograd#235]
How can I make a function like this work with autograd, given that assignment is forbidden?

```python
def func(a, b):   # a and b are scalars
    m = np.zeros((10, 10))
    m[5,7] = a
    m[3,6] = b
    return m
```

**Comment by mattjj** [comment]
Here are two ways to do it. Because `func` is a linear map, you can implement it in a sparse matrix form treating `a` and `b` as coefficients on fixed basis elements:

```python
def func(a, b):
    def one_hot(i, j):
        out = np.zeros((10, 10))
        out[i, j] = 1
        return out
    return a * one_hot(5, 7) + b * one_hot(3, 6)
```

If the indices (5, 7) and (3, 6) are really constants (or you're going to call `func` many times with the same values for those indices) you can make that more efficient with staged evaluation, so that the basis elements aren't re-allocated on every invocation.

Another way to do it is to write your own primitive, which is probably both more straightforward and more performant:

```python
@primitive
def func(a, b):
    m = np.zeros((10, 10))
    m[5, 7] = a
    m[3, 6] = b
    return m
func3.defvjp(lambda g, ans, vs, gvs, a, b: g[5, 7], argnum=0)
func3.defvjp(lambda g, ans, vs, gvs, a, b: g[3, 6], argnum=1)
```

Inside a primitive, there are no autograd boxed values; everything is raw numpy, so you're back in the world you're used to. You have to define any vjp's you need for your primitives, though.

When writing custom primitives, `check_grads` is your friend!

Side notes: of course, you only need to do this if you're going to differentiate through `func`. Assignment into autograd's ArrayNodes is not supported, but when you're using `autograd.numpy`, ArrayNodes are only created as necessary during tracing, i.e. when an `autograd.numpy` function gets an ArrayNode as one of its arguments; otherwise, it's just raw numpy as usual. In fact, the kind of assignment you wrote might work anyway, since `m` is being created as a zeros matrix and won't be an ArrayNode, though when `a` or `b` is an ArrayNode, the assignment would have to turn it into  an array with dtype object and things might get weird.

**Comment by eric-wieser** [comment]
> since m is being created as a zeros matrix and won't be an ArrayNode, though when a or b is an ArrayNode, the assignment would have to turn it into an array with dtype object and things might get weird.

So presumably allocating this as a `np.zeros((10, 10), object)` would also solve the problem?

**Comment by mattjj** [comment]
It might, but as I said, things get a bit weird. Autograd doesn't descend into data structures looking for Nodes, so when you pass around that object ndarray with Nodes inside, primitives will just call the underlying numpy functions on the array without unboxing the Nodes first. Most or all of those numpy primitives might still function properly, since they could just unpack the object array and dispatch to arithmetic operations defined on the objects contained in the ndarray, but I suspect at least some would be unhappy. Furthermore, if you returned an object ndarray like that to a function that you're differentiating with `jacobian`, I think you'd get a message that the output is independent of the input (since it looks like the output isn't itself a Node, even though it contains Nodes) and an incorrect zero value for the Jacobian.

The computation probably wouldn't be what you want anyway, since using object arrays kind of defeats the purpose of using a dense linear algebra library in the first place. The methods I suggested ensure that you're working with dense arrays of floats that are thinly boxed by autograd Nodes.

**Comment by eric-wieser** [comment]
> you can make that more efficient with staged evaluation,

Can you elaborate on that? In particular, it would be great if the `one_hot` call weren't recomputed when calculating gradients with respect to each of `a` and `b`

**Comment by mattjj** [comment]
Oh, it won't be recomputed, assuming you're just making one call to grad; that function is only evaluated on the forward pass. Constant arrays like those are cached for use in the backward (gradient) pass, and within one call to `grad` the same arrays would be reused for evaluating the partials with respect to `a` and `b`.

By staged evaluation, I was referring to making the forward pass more efficient, assuming you're running it more than once. Something like this:

```python
def one_hot(i, j):
    out = np.zeros((10, 10))
    out[i, j] = 1
    return out

def make_func(indices):
    basis = [one_hot(*idx) for idx in indices]
    def func(*vals):
        return sum(val * elt for val, elt in zip(vals, basis))
    return func

func = make_func([(5, 7), (3, 6)])  # basis is allocated here, reused across calls to func
```

**Comment by mattjj** [comment]
If you are differentiating with respect to `a` and `b` directly, rather than them being some intermediates in the computation, you can also get them both at once (without redoing the forward pass or backward pass) using `multigrad`, which is in convenience_wrappers.py. Check out that file, since there is a lot of functionality in there.

You can also do the same thing manually by writing a function that takes an `(a, b)` tuple argument instead of separate arguments (since autograd will happily differentiate with respect to a tuple argument).

**Comment by eric-wieser** [comment]
Thanks for that, I wasn't sure if `multigrad` was actually saving computation, or just providing syntactic sugar.

Is there any reason that there's no `multijacobian`? I've thrown together a function myself that does it inefficiently, but  presumably the forward pass could be shared there too?

**Comment by mattjj** [comment]
No particular reason, other than `grad` generally gets more attention than `jacobian`. There's actually more reason to write one for `jacobian`, actually, since you can't do the tuple trick I wrote above (because `jacobian` only works on array arguments).

Using `multigrad` (and the tuple trick with `grad`), both the forward and the backward passes are shared, i.e. there's only one of each. That's unlike the behavior inside `jacobian`, where a separate backward pass is used for each dimension of the output. If you wanted the Jacobian with respect to multiple arguments (i.e. to implement a `multijacobian`), you could also set something up to avoid redundant backward passes, i.e. you would still only require as many backward passes as output dimensions. (You would call a few more VJPs at the end, but you wouldn't be calling `backward_pass` any more.) That might be a good thing to add.

**Comment by mattjj** [comment]
Can we close this issue? If we want to make a feature request issue for `multijacobian`, that could be a separate issue with a more accurate title.
