### ISSUE TITLE
Recent commit "Added tests and fix for singleton array outputs" breaks higher order derivatives

### ISSUE THREAD

**Issue by jackkamm** [HIPS/autograd#24]
Hi,

This commit from earlier today, breaks some code I have. Unfortunately I am having a really hard time debugging and finding the location of the error, but here are some clues:

1) It only happens when I take a second-order derivative -- the first-order derivative of my function works fine.

2) The error occurs in numpy_extra.py, inside the inner lambda function defined in

untake.defgrad(lambda ans, x, idx, template : lambda g : take(g, idx))

3) Specifically, the error occurs because g is a 0-d array, array(float), and idx=0, and I get 
    IndexError: 0-d arrays can't be indexed

For now I am going to switch back to the previous commit, but will work on debugging it a bit more over the next couple days.

Also, are there any good strategies for debugging? I find it really difficult to trace errors once autograd goes into the backward_pass() function.

**Comment by duvenaud** [comment]
Ack, sorry.  I just reverted that commit.  It was trying to fix an issue relating to singleton array outputs, but since no one seems to have run into that issue on their own, I'll leave it until I have a more satisfactory solution.

I too have difficulties debugging on the backwards pass.  Usually we just add a ton of print statements to get an idea of what was going on, but we should probably learn to use conditional breakpoints or something more sophisticated.

If you send me the code that failed, I'll turn it into a test so that this won't happen again.

**Comment by jackkamm** [comment]
Thanks very much!

So, my code is large & messy right now. Hence the difficulty in tracing the error. I'm willing to share with you but, honestly, you probably don't want to go through the trouble of setting up and running it yet.

I'm in the process of cleaning up the project, to release it on github over the next week or two (hopefully). At that point it should be much easier to isolate the problem and create a minimal example test case. I'll stay in touch about that.

Thanks again for all the great work, I've found autograd to be a really useful tool.
