### ISSUE TITLE
Reusing calculations in both the function and derivatives

### ISSUE THREAD

**Issue by krey** [HIPS/autograd#241]
Brand new to automatic differentiation, sorry if this question doesn't make sense.
I am implementing the [Black-Scholes formula](https://en.wikipedia.org/wiki/Black%E2%80%93Scholes_model#Black.E2.80.93Scholes_formula) in Python and I would like to add it as a primitive in autograd. The Black Scholes formula is a scalar function of 4 scalar variables C(S, sigma, t, r).

There are non-trivial cancellations when taking derivatives, for instance dC/dS is just N(d_1), which is part of the calculation for C. The other partial derivatives "reuse" intermediate values from the calculation of C too.

Currently, I'm returning a tuple instead of a scalar. So C would look something like

```python
@primitive
def C(S, sigma, t, r):
    ...
    N_d_1 = ...
    ...
    value = ... N_d_1 ...
    return np.array([value, N_d_1])
```
and dC/dS just does `g[0] * ans[1]`. Is there a better way?

**Comment by mattjj** [comment]
This is a good question, but I don't think we have a better solution, at least not yet. The other ways we've tried to forward intermediate computations to the vjp end up breaking higher-order differentiation. I think the best current strategy is to return a tuple, as you're doing (though you can return a Python tuple instead of calling `np.array`, but I don't think there's a reason to prefer that for scalar values).

**Comment by krey** [comment]
@mattjj Thank you for the speedy response!
Is there anything I can do if I don't care about higher derivatives?

**Comment by mattjj** [comment]
(A fast response followed by a slow response!)

The thing to do is basically what you're doing now; you're only handling `g[0]` and not `g[1]` so higher-order derivatives won't work. Here's an example that @dougalm wrote at one point to explain the issue to me:

```python
import numpy as onp
import autograd.numpy as np
from autograd import grad, primitive

def exp2(x):
    return primitive_exp2(x)[0]

@primitive
def primitive_exp2(x):
    ans = onp.exp(x)
    temp = ans
    return ans, temp

def primitive_exp2_vjp(g_tuple, ans_tuple, vs, gvs, x):
    g, _ = g_tuple
    ans, temp = ans_tuple
    return g * temp

primitive_exp2.defvjp(primitive_exp2_vjp)

print grad(np.exp)(0.0)
print grad(grad(np.exp))(0.0)

print grad(exp2)(0.0)
print grad(grad(exp2))(0.0)
```

In words, if you don't define your vjp to also pull back derivatives along the auxiliary variables, but you do use the auxiliary variables in the vjp definition, then in effect autograd won't know about the dependence of the gradient on the auxiliary variables, so that when you go to differentiate again that dependence isn't handled and the second derivative is wrong.

**Comment by krey** [comment]
@mattjj: Thank you very much for the detailed answer. I guess I was wondering if there's an even less clean way of doing it in order to reduce autograd's overhead.

**Comment by krey** [comment]
@mattjj: Is there any reason you're not mentioning primitive_with_aux? My issue seems to be a duplicate of https://github.com/HIPS/autograd/issues/129

**Comment by mattjj** [comment]
Ah yes, primitive_with_aux was my initial confused attempt to deal with this kind of thing, but it doesn't actually do any more than what we've discussed here (just having the function return a pair, and breaking higher derivatives).

**Comment by mattjj** [comment]
I had forgotten about that issue, though, so thanks for cross-referencing it! Maybe we should close it too...

**Comment by krey** [comment]
@mattjj: Having a separate decorator for this is a valuable feature in my opinion!

It saves you the boilerplate in https://github.com/HIPS/autograd/issues/241#issuecomment-310861849
