### ISSUE TITLE
autograd consume too much memory and very slow

### ISSUE THREAD

**Issue by minhhg** [HIPS/autograd#244]
Hi,
I got a simple code  below
%------------------------------------------
`
import numpy as np
from autograd import grad

ITIME=1
returns = np.random.rand(10000, 75, 13)
x= np.random.rand(13)
horizon = 30
def obj(x):
    res  = np.cumprod(returns.dot(x), axis=ITIME)
    res1 = res[:, horizon-1]
    log_returns = np.log(res1)
    return -log_returns.mean()

gr = grad(obj)
print(gr(x))
%-----------------------------------------------
`
It was very slow and took a lot memory on 32Gb Ubuntu, python 2.7. It did not finish, I had to stop it until it crash. Any idea why?  Thanks, Minh

**Comment by j-towns** [comment]
Change
```python
import numpy as np
```
to
```python
import autograd.numpy as np
```
Also note that the gradient of `np.cumprod` isn't implemented in Autograd, so that isn't supported. And using `ndarray.dot` also won't work, you have to use the `np.dot(..., ...)` form.

BTW I ran your code and it crashes really badly on my machine, after about 15 seconds waiting I get the following error:
```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/jamietownsend/miniconda3/lib/python3.6/site-packages/IPython/core/application.py", line 255, in excepthook
    return crashhandler.crash_handler_lite(etype, evalue, tb)
  File "/Users/jamietownsend/miniconda3/lib/python3.6/site-packages/IPython/core/crashhandler.py", line 205, in crash_handler_lite
    traceback.print_exception(etype, evalue, tb)
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 486, in __init__
    _seen=_seen)
  [Previous line repeated 3 more times]
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 474, in __init__
    _seen=_seen)
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 474, in __init__
    _seen=_seen)
  File "/Users/jamietownsend/miniconda3/lib/python3.6/traceback.py", line 474, in __init__
    _seen=_seen)
  [Previous line repeated 487 more times]
RecursionError: maximum recursion depth exceeded

Original exception was:
Segmentation fault: 11
```
This shouldn't happen, it should fail with a Python/Autograd error rather than a seg fault. I'm not sure what's causing that though.

**Comment by mattjj** [comment]
You should read [the tutorial](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md), which includes both of the tips that @j-towns gave you.

This code, where I switched `cumprod` to `cumsum` just for testing, mostly worked for me, but revealed an autograd bug in the grad for `cumsum`:

```python
import autograd.numpy as np
from autograd import grad

ITIME=1
returns = np.random.rand(10000, 75, 13)
x= np.random.rand(13)
horizon = 30

def obj(x):
    res = np.cumsum(np.dot(returns, x), axis=ITIME)
    res1 = res[:, horizon-1]
    log_returns = np.log(res1)
    return -log_returns.mean()

print obj(x)
gr = grad(obj)
print(gr(x))
```

We should probably open an issue to add the grad of cumprod, if we don't have a feature request issue for that already. I remember trying it at one point, but IIRC handling zeroes gets tricky. In the meantime, it might work for your use case to use `cumsum` in combination with `exp` and `log`.

I'm going to close this issue because the problem was not importing `autograd.numpy` and using the wrong form of `dot`.

**Comment by jermwatt** [comment]
I gave a solution to this over at #257 which I think is good advice for folks in general: if a function is not yet built into `autograd` you can almost always build it yourself.  Thats the beauty of the tool.

You can define. `np.cumprod` by extending autograd by defining your own primatives (as nicely detailed in the [autograd tutorial document](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md)).  But this requires that you yourself understand how to implement its gradient.  

If you don't want to have to figure that out - take the easy way out (I often do):  define the function (here `np.cumprod`) whose gradient you are interested in computing using components that `autograd` already knows how to differentiate.  So -  in other words - create your own `np.cumprod` function using simple looping and `numpy` functions that are already built in, and then `autograd` can compute its gradient right away.  I built a version of `np.cumprod` over in  #257 that runs virtually just as fast as the original (for the example data provided here) and `autograd` can differentiate it just fine.
