### ISSUE TITLE
Is 'stop_gradient' supported?

### ISSUE THREAD

**Issue by BaiGang** [HIPS/autograd#256]
Can we mark a variable as a constant value, i.e do not propagate derivative calculation further?

For example, we have:
```
y = g(x) = 2 * x
z = f(x, y) = x * y
```
and we want to evaluate `\frac{\partial z}{\partial x}` which is supposed to be `y` (and its value is 2*x)  rather than 4*x (which is `\frac{\partial x * 2 * x}{\partial x}`).

So how to mark `y` or `g(x)` as 'gradient back propagation is stopped here'?

Thanks,
Gang

**Comment by mattjj** [comment]
You can use the `getval` function to do this. Basically, `getval` tells autograd to "consider this thing a constant" by unwrapping it from any tracing that autograd may be doing:

```python
from autograd import grad, getval

def g(x): return 2 * x
def f(x): return x * g(x)  # note only one argument, this evaluates f(g(x))

print grad(f)(1.)  # 4.0

def f2(x): return x * getval(g(x))
print grad(f2)(1.)  # 2.0
```

However, you can instead just use how partial derivatives work:

```python
def g(x): return 2 * x
def f(x, y): return x * y  # note two arguments, as in your code

x = 1.
print grad(f)(x, g(x))  # 2.0
```

My hunch is that wanting to use `getval`/`stop_gradient` is an artifact of thinking in terms of explicitly graph-based libraries (like Theano and TensorFlow), and correspondingly an artifact of thinking about differentiating variables with respect to other variables, leaving implicit the functions you're actually differentiating. By contrast, in autograd you take partial derivatives of functions, and it's easy to reason about differentiating with respect to one argument while holding the others fixed: that's what a partial derivative is!

Still, using `getval` might be more convenient, depending on how one's code is structured.

For another argument about where autograd-like conventions can be better, see the Prologue section of Sussman and Wisdom's [Functional Differential Geometry](https://www.dropbox.com/s/t3si4b99ijqyhyk/9580.pdf?dl=0) (that's the official PDF from MIT Press; it's an open-access book). (The same argument is also in the Preface section of their [Structure and Interpretation of Classical Mechanics](https://mitpress.mit.edu/sites/default/files/titles/content/sicm/book.html).) Notice that differentiation is of functions and is taken with respect to their positional arguments, rather than the more common convention of writing differentiation in terms of named input and output symbols. I think this positional argument notation comes from Spivak's Calculus on Manifolds from 1965. It really cleans up one's thinking about differentiation; the only problem with it is that it's not standard.

**Comment by BaiGang** [comment]
Thanks Matthew for the inspiring reply!

I like the idea that differentiation is of functions rather than some variables w.r.t others. And it's more natural to formulate the problem. Thanks again for the detailed explanations.
