### ISSUE TITLE
Inverse Matrix with autograd numpy

### ISSUE THREAD

**Issue by MiYi93** [HIPS/autograd#258]
Hey, i have an issue. I need to inverse a Matrix with autograd numpy(i can't find a method for that) and at the end i have to do the gradient out of it. I know that an inverse Matrix is not differentiable, but has some here an idea how to solve my problem. Is there a way to program that.

thanks

**Comment by mattjj** [comment]
I think you want the `np.linalg.inv` function, and you can get the autograd-wrapped version this way:

```python
import autograd.numpy as np
np.linalg.inv  # <- you want to call this function!
```

The matrix inverse function is differentiable for nonsingular matrices. You can find a brief discussion on p. 644 of [Boyd and Vandenberghe's Convex Optimization](http://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf). The basic idea is that if you think in terms of forming a local linear approximation to the inverse function at a point X in its domain, you can write (X + dX)^{-1} ≈ X^{-1} + X^{-1} dX X^{-1}, which suggests that if f(X) = X^{-1} then its Jacobian is given by ∂f(X)(Y) = X^{-1} Y X^{-1}. Because autograd uses reverse-mode autodiff, [we implement the adjoint of that linear operator, which basically means adding transposes](https://github.com/HIPS/autograd/blob/dc78f10b9b616654d69e39df38239107ed9b6250/autograd/numpy/linalg.py#L26).
