### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by juergspaak** [HIPS/autograd#271]
I tried to run the `tanh` example but got the following error:
`TypeError: Output [-0.9981779  -0.99804522 -0.9979029  ...,  0.9979029   0.99804522
  0.9981779 ] can't be cast to float. Function grad requires a scalar-valued function. Try jacobian or elementwise_grad.`

I assume that broadcasting is not working. If I run `grad(tanh)(1.0)` I get the correct result

**Comment by mattjj** [comment]
I suspect the issue is that you're using a previous version of autograd; the automatic vectorization feature was added relatively recently on master, and isn't yet reflected in the pip version.

Can you try running the example with master (or otherwise use the example files corresponding to the version of autograd you're using)?

**Comment by juergspaak** [comment]
Yes, I was already assuming, that I didn't have te newest version.
How can I chekc which version I have? `autograd.version`, `autograd.__version__` etc. didn't work. 

When will the automatic vectorization feature be added to the pip version? I would really like to install through `pip` as I'm not (yet) a big computer expert...

**Comment by mattjj** [comment]
I updated pypi last week.
