### ISSUE TITLE
cannot find gradients of np.linalg.eigh

### ISSUE THREAD

**Issue by gideonite** [HIPS/autograd#310]
When I run `grad(np.linalg.eigh)(np.eye(2))` I get an error

```
TypeError: No loop matching the specified signature and casting
was found for ufunc eigh_lo
```

Am I doing something wrong?

I think that is some kind of numpy type error. I'm having some trouble fixing the problem because I'm finding it difficult to grok what primitives are all about and how to inspect their contents. If you give me some pointers I'd be happy to look deeper into this.

**Comment by mattjj** [comment]
Do you think you might have forgotten to write `import autograd.numpy as np`?

That looks like an error caused by passing an Autograd-boxed value to a raw numpy kernel, instead of going through the thin wrapper provided by `autograd.numpy` primitives (which just unbox inputs and rebox outputs, recording the operation into a graph that is later used to propagate gradient information).

On the current master commit, I get the same error as you when I don't use `import autograd.numpy as np` and instead do `import numpy as np`. However, there are a couple more problems you'll run into when you fix the import. For one, `grad` only applies to scalar-output functions, and while it won't raise an error for vector- or matrix-output functions, it does something which might be surprising. Another is that `np.linalg.eigh` actually returns a pair (a vector of eigenvalues and a matrix of eigenvectors), so even `jacobian` won't like that kind of output. However, this code works for me:

```python
import autograd.numpy as np
from autograd import grad, jacobian

sym = lambda X: (X + X.T) / 2.
X = sym(np.random.randn(2, 2))
print grad(lambda X: np.linalg.eigh(X)[1])(X)
print grad(lambda X: np.sum(np.linalg.eigh(X)[1]))(X)  # actually does the same thing
```

There are a lot of places where `eigh` isn't differentiable, including the identity matrix, so watch out for nans!

**Comment by gideonite** [comment]
Aha, that's what I was missing! Thanks, I should have read the documentation more closely. It's clearly laid out here: https://github.com/HIPS/autograd/blob/master/docs/tutorial.md#how-to-use-autograd.

You mention that `grad` only applies to scalar valued functions. What if I define a scalar valued function like this:

```py
import autograd.numpy as np

def logdet(X):
    return np.sum(np.log(np.linalg.eigh(X)[0]))
```

Then I should be able to call `grad(logdet)(X)` and expect normal behavior right?

**Comment by gideonite** [comment]
Aha, I appear to have solved my problem. It's another error on my part. log is undefined on nonpositive numbers therefore, det needs to be nonnegative. One way to ensure this is to make X positive semi-definite. So similarly to how you defined `sym`, I defined `psd` as follows

```py
def psd(X):
    epsilon = 1e-4
    n,m = np.shape(X)
    I = np.eye(n)
    return np.dot(X,X.T) + epsilon * I
```
