### ISSUE TITLE
assert vspace(vjp_y) == x_vs

### ISSUE THREAD

**Issue by jluttine** [HIPS/autograd#335]
I must be missing something very obvious here, but why doesn't the below code work:

```python
from autograd import numpy as np
from autograd.extend import primitive, defvjp
from autograd.test_util import check_grads

@primitive
def f(x):
    y = np.zeros(2)
    y[0] = x[0] ** 2
    y[1] = x[0] + x[1]
    return y
 
def df(y, x):
    def _df(g):
        dy = np.zeros(2)
        dy[0] = 2 * g[0] * x[0]
        dy[1] = g[0] + g[1]
        return dy
    return _df

defvjp(f, df)
check_grads(f, modes=["rev"])(np.array([1, 2]))
```

I get the following error:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-33-d116044e6089> in <module>()
----> 1 check_grads(f, modes=["rev"])(np.array([1, 2]))

/.../lib/python3.5/site-packages/autograd/wrap_util.py in nary_f(*args, **kwargs)
     18             else:
     19                 x = tuple(args[i] for i in argnum)
---> 20             return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
     21         return nary_f
     22     return nary_operator

/.../lib/python3.5/site-packages/autograd/test_util.py in check_grads(f, x, modes, order)
     61             check_grads(grad_f, (0, 1), modes, order=order-1)(x, v)
     62     if 'rev' in modes:
---> 63         check_vjp(f, x)
     64         if order > 1:
     65             grad_f = lambda x, v: make_vjp(f, x)[0](v)

/.../lib/python3.5/site-packages/autograd/test_util.py in check_vjp(f, x)
     29 
     30     vjp_y = x_vs.covector(vjp(y_vs.covector(y_v)))
---> 31     assert vspace(vjp_y) == x_vs
     32     vjv_numeric = x_vs.inner_prod(x_v, vjp_y)
     33     vjv_exact   = y_vs.inner_prod(y_v, jvp(x_v))

AssertionError: 
```

I would have asked help on gitter, IRC or something similar but I couldn't find any such forum for Autograd.

**Comment by mattjj** [comment]
This issue tracker is the perfect place to ask for help!

This error message isn't very clear, but the issue is that you're passing in an integer array argument to `f`, namely `np.array([1, 2])`, but your VJP is returning a float64 array (because that's the default dtype for `np.zeros(2)`). I think you probably just want to pass in a float64 argument by using `np.array([1., 2.])`. Then this error should go away.

The VJP check fails, though. For first-order, you might want something like this:

```python
from autograd import numpy as np
from autograd.extend import primitive, defvjp
from autograd.test_util import check_grads

@primitive
def f(x):
    y = np.zeros(2)
    y[0] = x[0] ** 2
    y[1] = x[0] + x[1]
    return y
 
def df(y, x):
    def _df(g):
        dy = np.zeros(2)
        dy[0] = 2 * g[0] * x[0] + g[1]
        dy[1] = g[1]
        return dy
    return _df

defvjp(f, df)
check_grads(f, modes=["rev"], order=1)(np.array([1., 2.]))  # note order=1
```

However, that fails for second order because then `g` is an Autograd Box type and you can't stuff a Box type in the float64 array `dy`. There's an interesting asymmetry that is good to keep in mind: inside a primitive you can do whatever you want (i.e. no Boxes will ever appear), but VJP code isn't itself primitive. In other words, while 'anything goes' inside a primitive, you have to play by the rules in your VJP to allow higher-order autodiff. (Actually, you're free to make the VJP itself a primitive, but then if you want higher-order autodiff you'd need to define *its* VJP manually.)

Here's a VJP definition that works to arbitrary order:

```python
from autograd import numpy as np
from autograd.extend import primitive, defvjp
from autograd.test_util import check_grads

@primitive
def f(x):
    y = np.zeros(2)
    y[0] = x[0] ** 2
    y[1] = x[0] + x[1]
    return y
 
def df(y, x):
    def _df(g):
        dy0 = 2 * g[0] * x[0] + g[1]
        dy1 = g[1]
        dy = np.array([dy0, dy1])
        return dy
    return _df

defvjp(f, df)
check_grads(f, modes=["rev"])(np.array([1., 2.]))
```

**Comment by mattjj** [comment]
(Whoops, closed accidentally.) Please close the issue if this resolved your problem!

**Comment by mattjj** [comment]
Can we close this?

**Comment by jluttine** [comment]
I didn't yet test but I'm pretty sure the issue was about missing `order`. Thanks!
