### ISSUE TITLE
Tensordot broken

### ISSUE THREAD

**Issue by jchayat** [HIPS/autograd#360]
In the following example `foo` and `bar` are equivalent, however their gradient differs (`bar` being correct).

```python

def foo(x):
    return tensordot(x, [1.0, 1.0j], axes=([0], [0]))

def bar(x):
    return sum(x * [1.0, 1.0j])

>>> value_and_grad(foo)(array([1.0, 1.0]))
(array(1.+1.j), array([ 1.+1.j, -1.+1.j]))

>>> value_and_grad(bar)(array([1.0, 1.0]))
((1+1j), array([ 1., -1.]))
```

**Comment by jchayat** [comment]
Wait, bar seems wrong as well. should be 
```python
[1.0, -1.0j]
```

**Comment by jchayat** [comment]
I'm on python 3.6.3
autograd 1.2
numpy 1.14

**Comment by dougalm** [comment]
Thanks for the bug report. The problem is that value_and_grad doesn't accept complex-output functions. See #361. Added a check in deafd6d07b0c1fee444e9654ee4311daefddbb17.

**Comment by jchayat** [comment]
Well, here's a real-in, real-out function (using `tensordot` + complex internally) which still gives wrong answers.

Am I to understand that `value_and_grad` cannot be used with complex at all (even if the interface is real)?

```python
def foo(x):
    return absolute(sum(x * array([1.0, 1.0j]))) ** 2

def bar (x):
    return absolute(tensordot(x, array([1.0, 1.0j]), axes=([0], [0]))) ** 2


>>> value_and_grad(foo)(array([1.0, 1.0]))
(2.0000000000000004, array([2., 2.]))
>>> value_and_grad(bar)(array([1.0, 1.0]))
(2.0000000000000004, array([2.-2.j, 2.+2.j]))
```

**Comment by jchayat** [comment]
BTW,  are you familiar with [Wirtinger derivatives](https://en.wikipedia.org/wiki/Wirtinger_derivatives)?

**Comment by dougalm** [comment]
Oops, you're quite right. This is a serious bug. Thanks for following up on it even after I tried to dismiss it!

Tensordot is broken for mixed real-complex arguments. So are the the related functions dot, outer, matmul and kron (though not einsum because its vjp uses unbroadcast). The vjps should return values of the same type (real or complex) as the differentiated-with-respect-to input. We have an [explicit case for this in the unbroadcast part of the vjps for binops](https://github.com/HIPS/autograd/blob/deafd6d07b0c1fee444e9654ee4311daefddbb17/autograd/numpy/numpy_vjps.py#L562-L563), but not for these tensordots. Also, we don't test them against complex inputs. We [used to check at each vjp application that result was of the expected type and shape](https://github.com/HIPS/autograd/blob/b4a0d2f77d6ce8f853cb1d8277d4827439389e6a/autograd/core.py#L24) but we removed those asserts in the interests of performance. At least they would have thrown a helpful error message in your case.

I just pushed 91dd350f1cb74cad5f65fcba0fa2eb24e83c818a which should fix the problem.

> BTW, are you familiar with Wirtinger derivatives?

I've never used them, but we did consider Wirtinger derivatives when we were deciding how to implement support for complex numbers. If they're useful to you, it would be easy to add a function to differential_operators.py that takes the result of make_vjp and expresses it in terms of Wirtinger derivatives.

> Am I to understand that value_and_grad cannot be used with complex at all (even if the interface is real)?

No. You should definitely be able to use complex numbers internally. This is a bug with the primitive derivative of tensordot and friends. Thanks for catching it.

**Comment by jchayat** [comment]
did
`pip install git+https://github.com/HIPS/autograd.git@91dd350f1cb74cad5f65fcba0fa2eb24e83c818a`

example above still gives me the same result

**Comment by jchayat** [comment]
Scratch that, it works.

Thanks!
