### ISSUE TITLE
Complex derivative wrong

### ISSUE THREAD

**Issue by jchayat** [HIPS/autograd#361]
```python
>>> value_and_grad(lambda x: x)(1.0j)
(1j, (1+1j))
```

**Comment by dougalm** [comment]
Thanks for catching that! By design, `autograd.grad` and `autograd.value_and_grad` only apply to functions with real-valued scalar outputs. I just added a check to `value_and_grad` so your example now throws an error.

If you're interested in complex derivatives of holomorphic functions, you can use `autograd.holomorphic_grad`. We don't have a `value_and_holomorphic_grad` (it would get out of hand if we created a 'value_and_*' for all the functions in autograd.differential_operators) but you can easily create your own using `grad`, `value_and_grad` and `holomorphic_grad` in [differential_operators.py](https://github.com/HIPS/autograd/blob/master/autograd/differential_operators.py) as examples. They're all simple wrappers around `autograd.core.make_vjp`. Hope that helps!

**Comment by dougalm** [comment]
Check added in deafd6d07b0c1fee444e9654ee4311daefddbb17.
