### ISSUE TITLE
Pickling grad functions

### ISSUE THREAD

**Issue by mcleonard** [HIPS/autograd#38]
Hello! I'm attempting to use autograd gradient functions with Python's multiprocessing package. The package passes data to the processes it creates by pickling all the objects. When I try to pickle a grad func, I get:

    PicklingError: Can't pickle <function grad.<locals>.gradfun at 0x10abaf048>: 
         attribute lookup grad_logp_wrt_argnum_0 on autograd.core failed

When trying to pickle the function, Pickle needs to know about `grad_logp_wrt_argnum_0` so it needs to be in the name space. But I'm not sure how to get this object from autograd. It's cool if I need to find another way to do my parallel stuff, but I'm wondering if it is possible to make the grad functions pickleable.

Great package, this stuff is amazing.

**Comment by mcleonard** [comment]
Just as an update, I worked around it. I created the grad functions after the containing objects get passed to the processes.

**Comment by mattjj** [comment]
Two semi-related thoughts:

First, you generally can't pickle dynamically created functions:

```python
In [1]: def foo():
   ...:     def bar():
   ...:         pass
   ...:     return bar
   ...:

In [2]: f = foo()

In [3]: import cPickle as pickle

In [4]: with open('blah','w') as outfile:
   ...:     pickle.dump(f, outfile, protocol=-1)
   ...:
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-4-936b70c81ccd> in <module>()
      1 with open('blah','w') as outfile:
----> 2     pickle.dump(f, outfile, protocol=-1)
      3

PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

To be picklable, functions need to be defined at the module level, which grad functions aren't. I think there are some other multiprocessing libraries that use different serialization techniques (and maybe the dill library) and can handle this case, but I'm not familiar with them.

Second, you may be able to avoid pickling entirely by passing a reference to this generated grad function through through a global (i.e. module-level) variable instead of as an argument, if that's possible with your program design. That exploits the fact that multiprocessing calls fork, and forked processes have (copy-on-write) access to their parents' virtual address spaces. That technique can significantly reduce overhead as well, since it means less serialization and IPC. I found something of a [minimal example](https://gist.github.com/mattjj/c329eb94f5769ef78d17) I wrote a while ago, but if you're interested in more let me know.

**Comment by mattjj** [comment]
I'm going to close this because it's not an autograd-specific issue; any method for pickling (or doing multiprocessing with) inner functions should work.
