### ISSUE TITLE
Include tests in PyPI source tarball?

### ISSUE THREAD

**Issue by jluttine** [HIPS/autograd#404]
Would it be possible to include the tests in the PyPI source tarball? I think this is good practice so people can check that the package works after installing it.

**Comment by agriyakhetarpal** [comment]
Hi, @jluttine – thanks for opening this request. I know that this issue was opened more than six years ago, but this has now been implemented with #626, where we migrated to `hatchling` for the build backend, and the `tests/` folder is included in the sdist since the recent v1.7.0 release: https://pypi.org/project/autograd/1.7.0/ and will continue to be available for subsequent releases. I can close this issue as resolved for now, please feel free to reach out if you have any more suggestions!
