### ISSUE TITLE
Gradient of norm doesn't account for axis argument

### ISSUE THREAD

**Issue by alquraishi** [HIPS/autograd#42]
I see that Autograd currently implements the gradient of norm in numpy.linalg, but it doesn't handle any of its options. Support for the "axis" option would be useful.

**Comment by a1k0n** [comment]
Seconded; just ran into this.

**Comment by a1k0n** [comment]
though FWIW, `np.sqrt(np.sum(x*x, axis=1))` does work as a workaround for L2 norm

**Comment by mattjj** [comment]
Try out the commit I just pushed, and please reopen the issue if it's busted.

Gradients of `np.linalg.norm` should now support the `axis` argument and I also added support for the `ord` argument for vector p-norms with p > 1 using [a formula on wikipedia](https://en.wikipedia.org/wiki/Norm_(mathematics)#p-norm). I didn't add support for improper p-norms or matrix norms other than Frobenius norm, though there's a nice writeup of the reverse-mode grad of spectral norm in [Giles's pdf](https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf). I added some basic tests as well.

**Comment by a1k0n** [comment]
Seems to work fine, thanks!

**Comment by Strateus** [comment]
```
>>> _norm.shape
(14,)
>>> gz.shape
(14, 128)
>>> x.shape
(14, 128)
>>> grad = autograd.numpy.linalg.make_grad_norm(_norm, x, 2, 1)
>>> grad(1).shape
(14, 128)
>>> grad(gz).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\autograd\numpy\linalg.py", line 59, in norm_grad
ValueError: operands could not be broadcast together with shapes (14,128) (14,) 
>>> 
```

What i should supply into grad func? gradient from top layers? In this case it raises value error. Or i am doing something wrong?

**Comment by mattjj** [comment]
Can you say a bit more with what you're trying to do with calling `make_grad_norm`? And if you're having a problem, can you open a new issue instead of commenting on this closed one?

Users wanting to compute a gradient should only need to call `np.linalg.norm` as usual, not `make_grad_norm`:

```python
In [1]: from autograd import grad

In [2]: import autograd.numpy as np

In [3]: grad(lambda x: np.linalg.norm(x))(np.ones(3.))
Out[3]: array([ 0.57735027,  0.57735027,  0.57735027])

In [4]: grad(lambda x: np.linalg.norm(np.linalg.norm(x, axis=1), axis=0))(np.ones((3,3)))
Out[4]:
array([[ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333]])
```

The function returned by `make_grad_norm` takes as its argument the gradient of the final output with respect to the value returned by `np.linalg.norm`. In particular, if the arguments to `np.linalg.norm` were as in `np.linalg.norm(x, axis=1)` where `x` had shape (14,128), then the argument to the function returned by `make_grad_norm` should have shape (14,) (and its output will have the same shape as `x`).

**Comment by Strateus** [comment]
Im making L2 norm layer for Chainer, so i need linalg.norm and its gradient wrt its inputs and top gradient.
I am just doing np.divide after np.linalg.norm and that i seems need to take grad first, so shape whould be (14,) after that. Im now trying to figure out how to take grad of np.divide now.

As for new issue, i was not sure if its my bug or not, so why would i create new issue if im mistaken, to not flood your Issues. Thank you for the help.
