### ISSUE TITLE
assertions in derivatives

### ISSUE THREAD

**Issue by jackkamm** [HIPS/autograd#43]
Sometimes, if I have a function with assertions inside, and I take the gradient of the function, it breaks. For example, the following breaks for me:

````python
import autograd.numpy as np
from autograd import grad

def foo(x):
    assert np.allclose(x, (x*3.0)/3.0)
    return np.sum(x)

g = grad(foo)
g(np.array([1.0,2.0,3.0]))
````
The assertion causes a
````python
TypeError: Can't differentiate wrt <type 'numpy.bool_'>
````

**Comment by mattjj** [comment]
I attempted a fix, though I could use another set of eyes on it (paging @dougalm and @duvenaud!).

I think this effect is an instance of a more general problem: if we evaluate nondifferentiable functions on the forward pass (e.g. because the grads aren't implemented or because the derivative doesn't make sense because the output is a bool or something), but those values don't affect the output (e.g. because they're in an assert), we don't need to throw an error. I think that means we don't want to throw such errors on the forward pass, and instead we want to throw them on the backward pass (i.e. when we have to actually perform a bad operation in the computation of the gradient we care about).

I attempted to push these errors into the reverse pass with c38186c. Basically, I added a reverse node type that blows up when encountered.

In addition to the test you provided, I tested two tweaked versions:

```python
import autograd.numpy as np
from autograd import grad

def foo(x):
    assert np.allclose(x, (x*3.0)/3.0)
    return np.sum(x)

g = grad(foo)
print g(np.array([1.0,2.0,3.0]))

def foo(x):
    assert np.allclose(x, (x*3.0)/3.0) + 1
    return np.sum(x)

g = grad(foo)
print g(np.array([1.0,2.0,3.0]))

def foo(x):
    return np.allclose(x, (x*3.0)/3.0)

g = grad(foo)
print g(np.array([1.0,2.0,3.0]))
```

The first two run fine and the last one blows up, as intended.

What do you guys think? And was rolling this into master premature?

**Comment by jackkamm** [comment]
Thanks for fixing this @matjj. I don't know enough to make specific comment about your solution. But I had a thought:

It is my understanding that the boolean operators ==, <, >, etc., all work fine with autograd. Would it be possible to simply treat numpy.isclose and numpy.allclose in the same manner?

**Comment by mattjj** [comment]
That's a great point! Those ops are just wrapped as primitives, and so there's no problem on the forward pass. However, they also don't lead to errors on the backward pass, and I think we want those errors:

```python
import autograd.numpy as np
from autograd import grad

print grad(lambda x: x > 5)(10.)  # prints 0 and the 'independent of input' warning
```

Hmm...
