### ISSUE TITLE
forward mode Jacobian

### ISSUE THREAD

**Issue by plisdku** [HIPS/autograd#439]
I have a need for a fast, forward-mode Jacobian and I see such a thing was implemented (partially? completely?) but not merged last year because there was no solid use case.  I wonder what the barriers are to finishing/merging that project?  (If there is more work to do maybe I can help.)

My application is a curve-fitting problem in spectroscopy.  My model function accepts order of one or several dozen parameters and produces order of 1000 data points.  The model function is horrid and also under development so it would be splendid to get the derivatives "for free".

It works in reverse mode on the sum of squares of the residual but I need the whole Jacobian because I want to use Levenberg-Marquardt.

**Comment by j-towns** [comment]
Hi there, you can use [this](https://github.com/HIPS/autograd/blob/master/autograd/differential_operators.py#L16) (undocumented) function, which is currently our forward mode API.

Given a function `f`, vectors `x` and `v` in the domain of  `f`, `make_jvp(f)(x)(v)` computes both `f(x)` and the Jacobian of `f` evaluated at `x`, right multiplied by the vector `v`.

A simple example of how to use it:
```python
In [1]: from autograd import make_jvp

In [2]: import autograd.numpy as np

In [3]: A = np.random.randn(2, 2)

In [4]: A
Out[4]:
array([[ 1.97816866,  0.38463178],
       [-0.97767818, -1.82779227]])

In [5]: def f(x):
   ...:     return np.dot(A, x)

In [6]: x = np.zeros(2)

In [7]: jvp_f_x = make_jvp(f)(x)

In [8]: jvp_f_x(np.array([1, 0]))  # f(0) and first column of f's Jacobian at 0
Out[8]: (array([0., 0.]), array([ 1.97816866, -0.97767818]))

In [9]: jvp_f_x(np.array([0, 1]))   # f(1) and second column of f's Jacobian at 1
Out[9]: (array([0., 0.]), array([ 0.38463178, -1.82779227]))
```
To get the full Jacobian of `f` you just need to write a loop to evaluate make_jvp(f)(x)(v) for each `v` in the standard basis of `f`'s domain. Our [reverse mode Jacobian operator](https://github.com/HIPS/autograd/blob/master/autograd/differential_operators.py#L55) works in the same way.

**Comment by j-towns** [comment]
Ah yes, for maximal caching (minimum overall computation), we've got [`make_jvp_reversemode`](https://github.com/HIPS/autograd/blob/65c21e2975fd4d0c6e979c248ee4407e94ed15bf/autograd/differential_operators.py#L104). That will do one extra pass through the graph the first time it's called but will store the values of everything in the computation of `f`. That means it takes 1.5x as much time as `make_jvp` for computing the first jacobian-vector-product, then roughly 0.5x for each subsequent vector (evaluated at the same point x). I should have mentioned this method before.
```python
In [1]: import autograd.numpy as np

In [2]: from autograd.differential_operators import make_jvp_reversemode

In [3]: A = np.random.randn(100, 100)

In [4]: def f(x):
   ...:     return np.dot(A, x)

In [5]: f_jvp_fast = make_jvp_reversemode(f)(np.zeros(100)) # This precomputes things

In [6]: v = np.random.randn(100)

In [7]: %timeit f_jvp_fast(v)
14.8 µs ± 42.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [8]: from autograd import make_jvp

In [9]: f_jvp_slow = make_jvp(f)(np.zeros(100))

In [10]: %timeit f_jvp_slow(v)
30.9 µs ± 222 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
The time saving comes form the fact that line `[5]` computes things that are shared between different derivative computations. `[5]` can be quite slow, depending on `f`, so you should profile things to make sure you're getting a speedup overall.
```
In [11]: %timeit make_jvp_reversemode(f)(np.zeros(100))
151 µs ± 217 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
For computing the full Jacobian of `f` there clearly would be a significant speedup from using this 'caching' trick. I wrote a [blog post](https://j-towns.github.io/2017/06/12/A-new-trick.html) about this method if you're interested.

It's also worth noting that this method is not theoretically optimal, because it passes through the graph one more time than is necessary. However it was straightforward to implement using the solid reverse mode that we already had. We will, at some point, get round to implementing proper (optimal) forward mode with caching.

**Comment by saugatkandel** [comment]
Tagging on to this, I am also trying to implement the Levenburg algorithm using autograd, but for complex numbers. The jvp code does not seem to work in this scenario. Here is a minimal working example (I can't get the ipython formatting right). Any suggestions?



```python
import autograd as ag
from autograd import numpy as np
from autograd.test_util import make_numerical_jvp
```


```python
f = lambda x: np.abs(x)

x = np.ones(5, dtype='complex128')
h = np.random.randn(x.size) + 1j * np.random.randn(x.size)
```


```python
jacf = ag.jacobian(f)
jacval = jacf(x)

jacval @ h
```




    array([-0.48614138+0.46906303j, -0.0906297 -0.05906721j,
           -0.00288325-0.09686726j,  1.31587973-2.67146718j,
            1.436558  -0.08866648j])




```python
jvpfun1 = ag.make_jvp(f)(x)
jvpfun1(h)
```




    (array([1., 1., 1., 1., 1.]),
     array([-0.48614138, -0.0906297 , -0.00288325,  1.31587973,  1.436558  ]))




```python
jvpfun2 = ag.differential_operators.make_jvp_reversemode(f)(x)
jvpfun2(h)
```




    array([-0.48614138, -0.0906297 , -0.00288325,  1.31587973,  1.436558  ])




```python
jvpfun3 = make_numerical_jvp(f, x)
jvpfun3(h)
```




    array([-0.48614138, -0.0906297 , -0.00288325,  1.31587973,  1.436558  ])

**Comment by j-towns** [comment]
The way reverse mode treats complex functions is a bit different to forward mode. For reverse mode see [here](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md#complex-numbers), for forward mode the convention is briefly described in [this comment](https://github.com/HIPS/autograd/issues/179#issuecomment-273851678) (as I said before forward mode is generally not yet well documented).

**Comment by saugatkandel** [comment]
Thanks for the information! I will try to work around that and see how it goes.

**Comment by j-towns** [comment]
Gonna close this for now.

**Comment by saugatkandel** [comment]
Thanks for the heads up! I have been busy with other projects, but I might have something to contribute to this discussion, more so on the Tensorflow side of things. I will comment on your blog post when I have a bit more time.
