### ISSUE TITLE
Jacobian and aux

### ISSUE THREAD

**Issue by johannbrehmer** [HIPS/autograd#442]
Hi,

Is it possible to combine the functionality of `jacobian()` and `grad_and_aux()`? My code is basically

```
def f(x, y):
    # ...
    z = [some_function(x, y), other_function(x, y)]
    aux = last_function(x, y)
    return z, aux
```

and I need the Jacobian dz/dx as well as the unmodified `aux`.

`grad_and_aux()` only seems to support scalar functions, and `jacobian()` and `elementwise_grad()` don't seem to support the passing through of the second output.  Due to some stochasticity in the functions it is impractical to use two separate calls to `f(x,y)` and its derivative.

Thanks a lot,
Johann

**Comment by jermwatt** [comment]
Looking at the code for those convenience functions - including `jacobian`, `grad_and_aux`, etc., - [here](https://github.com/HIPS/autograd/blob/master/autograd/differential_operators.py) - you can create a slightly adjusted version of e.g., `jacobian` that returns the function evaluation (denoted `ans`) along with the gradient evaluation, since its computed in forward sweep.  Its indeed computed in `jacobian` but simply not returned along with the gradient evaluation.  This will also compute / return the gradient of `aux`, but if this computation is not too great you'll be fine following the below.

Here's the original `jacobian` function:

```
def jacobian(fun, x):
    vjp, ans = _make_vjp(fun, x)
    ans_vspace = vspace(ans)
    jacobian_shape = ans_vspace.shape + vspace(x).shape
    grads = map(vjp, ans_vspace.standard_basis())
return np.reshape(np.stack(grads), jacobian_shape)
```

and here's the slightly adjusted version that just returns `ans` along with the gradient evaluation which you can define / use locally.

```
def my_jacobian(fun, x):
    """
    slightly adjusted 'jacobian' function that returns function eval
    as well as gradient eval
    """
    vjp, ans = _make_vjp(fun, x)
    ans_vspace = vspace(ans)
    jacobian_shape = ans_vspace.shape + vspace(x).shape
    grads = map(vjp, ans_vspace.standard_basis())
    return ans, np.reshape(np.stack(grads), jacobian_shape)
```

I tried this out on the following test function and it works

```
def f(x,y):
    # define functions to differentiate with respect to
    func_1 = lambda x,y: x + y
    func_2 = lambda x,y: x*y
    func_3 = lambda x,y: np.sin(x)*y
    z = np.array([func_1(x,y) ,func_2(x,y),func_3(x,y)])
    return z
```

Here's the full chunk of code defining `my_jacobian` including the imports (blindly copied and pasted from the convenience page, with local imports re-assigned as necessary)

```
from __future__ import absolute_import
from functools import partial
from collections import OrderedDict
from inspect import getargspec
import warnings

from autograd.wrap_util import unary_to_nary
from autograd.builtins import tuple as atuple
from autograd.core import make_vjp as _make_vjp, make_jvp as _make_jvp
from autograd.extend import primitive, defvjp_argnum, vspace

import autograd.numpy as np

make_vjp = unary_to_nary(_make_vjp)
make_jvp = unary_to_nary(_make_jvp)

@unary_to_nary
def my_jacobian(fun, x):
    """
    slightly adjusted 'jacobian' function that returns function eval
    as well as gradient eval
    """
    vjp, ans = _make_vjp(fun, x)
    ans_vspace = vspace(ans)
    jacobian_shape = ans_vspace.shape + vspace(x).shape
    grads = map(vjp, ans_vspace.standard_basis())
    return ans, np.reshape(np.stack(grads), jacobian_shape)
```

**Comment by johannbrehmer** [comment]
Thanks a lot! I tried something similar but didn't get it to work -- this was very clear and helpful!

**Comment by jermwatt** [comment]
No problem - glad it helped!
