### ISSUE TITLE
Python 3 syntax errors: print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [HIPS/autograd#451]
https://travis-ci.org/HIPS/autograd/jobs/459340911#L1038-L1050

**Comment by j-towns** [comment]
Hey there, thanks for raising this. I think all of the flake8 E999s are caused by this issue, which appears multiple times in the examples (which are not tested by Travis). If you were up for submitting a pr to fix this that would be fantastic. Just need to do
```
from __future__ import print_function
```
at the top of the offending files and change `print ...` to `print(...)`.
