### ISSUE TITLE
Dynd support

### ISSUE THREAD

**Issue by datnamer** [HIPS/autograd#51]
Dynd is a next generation array library for python, with lots of cool features like JIT compilation, heterogenous data, user defined data types, missing data support, type checking etc https://speakerdeck.com/izaid/dynd 

Wonder if there is interests from either HIPS or dynd devs  @izaid , @insertinterestingnamehere or @mwiebe in integrated this with Dynd (or atleast leaving in hooks for future funcitonality or cooperation later on?) 

Both are cool libraries and would hate to have the python community having to choose between them for projects.

**Comment by mwiebe** [comment]
This project is really cool, hey @duvenaud! I think it could map onto the Python exposure of DyND very similarly to how it maps onto NumPy.

Within DyND, I was imagining eventually adding dual numbers, roughly as described in http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.89.7749&rep=rep1&type=pdf, for automatic differentiation. Each scalar would be replaced by a fatter representation which includes the scalar value and one or more partials.

**Comment by mattjj** [comment]
DyND looks great! I tend to use vanilla homogeneous ndarrays myself, but I'm sure others could benefit from heterogeneous data types. What's the best place to read about the JIT compilation features?

Using a dual number type is a slick way to implement forward-mode automatic differentiation. However, autograd implements reverse-mode automatic differentiation, which is generally more efficient for functions R^n -> R^m when n > m. Since in optimization we usually want to differentiate objective functions which look like R^n -> R, maybe with very large n when neural nets are involved, reverse-mode autodiff is generally preferred.

**Comment by mwiebe** [comment]
My intuition suggests that forward mode could be inlined/jitted quite effectively, while reverse mode needs to collect the expression and reverse through it, so would typically be more dynamic. Do you have a good reference or benchmarks explaining the performance differences between them?

**Comment by mattjj** [comment]
That sounds right to me about JITing (Julia with a [DualNumber type](https://github.com/mattjj/autodiff/blob/master/forward_mode.jl) would do that right now). But even a big constant-factor speedup from compilation probably can't make up for the algorithmic disadvantage of forward mode (for the use cases I'm thinking of).

I think the main autograd overhead is exactly what you say: building and then traversing the computation graph, which is kind of like running an interpreter within Python's VM. Other people have brought up wanting to apply some kind of existing Python JIT tech to autograd (e.g. #47) but really we'd have to first compile autograd's representation to one of these languages (e.g. Python or numba). (Actually, since control flow might change the computation graph from execution to execution, even that would only apply to computation graphs that don't change from evaluation to evaluation, though that's a nice special case to handle.)

The others might be able to give you better refs but I get the impression that the gold standard is [Barak Pearlmutter's work](http://www.bcl.hamilton.ie/~barak/publications.html), like maybe [this brief intro](http://arxiv.org/pdf/1404.7456v1.pdf). I don't know of benchmarks, but the gap between forward-mode and reverse-mode can be made arbitrarily large just by scaling the problem dimensions, so any constant-factor implementation differences (like benchmarks would test) probably wouldn't be very enlightening.

**Comment by mattjj** [comment]
This is probably a much better place to read good Julia autodiff code: http://www.juliadiff.org/.

**Comment by datnamer** [comment]
@mattjj  wow those are some cool autodiff packages. Is BIDS going to be switching to Julia at some point?

**Comment by duvenaud** [comment]
Hi @mwiebe !  Long time no see.

As Matt said, reverse-mode is the only scalable approach for differentiating vector-input functions.  However, autograd might be able to support Dynd just by wrapping all its operations, as we did with ndarray.

By the way, you might get a kick out of this:  We implemented the reverse-mode derivative of np.einsum().  It just rearranges the inputs and the specification string a little.
https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_grads.py#L343

We love einsum. Here's an example using it with autodiff to vectorize inference in a Bayesian deep net:
https://github.com/HIPS/autograd/blob/master/examples/bayesian_neural_net.py
https://github.com/HIPS/autograd/blob/master/examples/bayesian_neural_net.png


Cheers,
David

**Comment by mattjj** [comment]
@datnamer What's BIDS?

I've been a Julia admirer since it was first announced (and we went to Jeff's thesis defense!) but I don't plan to switch in the near future.

**Comment by datnamer** [comment]
@mattjj ... sorry I meant HIPS :) This is BIDS: http://bids.berkeley.edu/

**Comment by mattjj** [comment]
I thought that was what you meant, and I knew BIDS sounded familiar. No, no switching plans yet; Python is being very good to us.

So what's our plan on this issue? Is there any immediate desire for some DyND features, or should these projects just be generally aware of each other and we'll see if crossover opportunities arise?

**Comment by izaid** [comment]
Hey guys! Just chiming in. I'm one of the other DyND developers. If you have particular feature requests, we'd for sure like to hear them.

**Comment by datnamer** [comment]
@izaid @mattjj Myself (and atleast the [Pymc](https://github.com/pymc-devs/pymc3/issues/708) crew and there have been some issues in statsmodels and [scipy](https://github.com/scipy/scipy/pull/4979) )  would love fast autodiff in python integrated with stuff like numba and dynd. 

Should I open an issue in one of those projects?

**Comment by datnamer** [comment]
Maybe autodiff can live in blaze at a higher level/with multiple backends using symbolic diff on the expression graph.

**Comment by mattjj** [comment]
I think the conversation here ended up being fairly similar to #47, so I'm going to close this issue to consolidate the discussion about "integrate with next-gen stuff like numba and dynd". Please reopen if there's any dynd-specific stuff we need to track here.
