### ISSUE TITLE
create your own primitive for matrix valued function

### ISSUE THREAD

**Issue by bpriviere** [HIPS/autograd#532]
Is it possible to create a primitive for a matrix valued function, ie func(x) = y where x is a vector and y is a matrix

For example, if I have matrix, A:  
A = [ 
   [x[0], x[1]]. 
   [x[3], x[4]] ]
I would like to give autograd the jacobian dA/dx as: 
dA/dx = [ 
   [[1,0,0,0]. [0,1,0,0]],
   [[0,0,1,0], [0,0,0,1]]]

If possible, can you please provide an example for this case? I have been using defvjp and having dimensional mismatch issues.

**Comment by momchilmm** [comment]
Autograd doesn't (directly) compute the jacobian of intermediate operations. Instead what you have to define is the vector-jacobian product `vjp`. So instead of telling autograd how to compute dA/dx, you have to tell it (using `defvjp`) how to compute the product `np.dot(dfdA, dAdx)`, where df/dA is some gradient "flow" coming from the subsequent operations which used `A` on the forward pass. For your particular example, I think *something* like this should work, as long as `x` always has shape (4, ) :

```
def A_vjp(A, x):
    dAdx = np.array([[[1,0,0,0], [0,1,0,0]], [[0,0,1,0], [0,0,0,1]]])
    return lambda v: np.dot(v, dAdx)
defvjp(A, A_vjp)
```

**Comment by bpriviere** [comment]
Thanks for your quick response. Unfortunately the simple np.dot did not work, I still get a dimension mismatch error in my case. 

However, by considering the dimension of the forward pass, as you mention, I was able to fix my problem by using the np.tensordot function. Something like this: 

def A_vjp(A, x):
    dAdx = np.array([[[1,0,0,0], [0,1,0,0]], [[0,0,1,0], [0,0,0,1]]])
    return lambda v: np.tensordot(v, dAdx)
defvjp(A, A_vjp)

I matched the output of A_vjp (ie product of dfdA and dAdx) to be the same dimension as dfdx.
