### ISSUE TITLE
Release new version 1.6.3 on PyPI

### ISSUE THREAD

**Issue by bittner** [HIPS/autograd#616]
A stable version of Autograd was last [released on PyPI](https://pypi.org/project/autograd/#history) on 23 June 2023 (commit 1bb5cbc2). Afterwards, a few investments were made that make sure Autograd can continue to be installed successfully (e.g. #602). Those changes are still unreleased.

It would help if a new release on PyPI were made.

---
_P.S.:_ As explained in https://github.com/HIPS/autograd/pull/605#issuecomment-1815200073, the only thing that needs to be done is _push a Git tag_ in order to trigger the automatic release process. As a one-time prerequisite, credentials from PyPI need to be configured on GitHub beforehand.

**Comment by agriyakhetarpal** [comment]
An environment for PyPI has now been set up. @fjosw and I shall be looking into getting this done in the coming days. We were thinking of incorporating NumPy v2 support (#618) with it, so we might as well bump it to version 1.7.0. @j-towns, I question I have is whether it would be a good idea to do a pre-release first with NumPy v2.0.0rc2 or if we should bump to v2.0.0 stable directly? I suppose the latter would be better since ABI remains stable between both, and I've found that it's easier to work with bounds when they don't specify pre-releases.

**Comment by j-towns** [comment]
Bumping straight to 2.0.0 sounds simpler, so I would probably do that.

**Comment by agriyakhetarpal** [comment]
New release is up, though we bumped to v1.7.0 directly: https://github.com/HIPS/autograd/releases/tag/v1.7.0 🎉 so we can close this.
