### ISSUE TITLE
usage question of defgrad and gradmaker from numpy.divide

### ISSUE THREAD

**Issue by Strateus** [HIPS/autograd#73]
Im trying to implement a layer for conv network, here is my code:

```
class L2Normalize(Function):
    
    def forward(self, inputs):
        xp = cuda.get_array_module(*inputs)
        x, = inputs
        if type(x) is cuda.ndarray:
            Xnp = cuda.cupy.asnumpy(x)
            self._norm = xp.asarray(np.linalg.norm(Xnp, ord=2, axis=1), dtype=xp.float32)
        else:
            self._norm = np.linalg.norm(x, ord=2, axis=1)
        z = xp.divide(x, xp.expand_dims(self._norm, axis=1))
        return z,

    def backward(self, inputs, grad_outputs):
        xp = cuda.get_array_module(*inputs)
        x, = inputs
        gz, = grad_outputs
        gx = xp.expand_dims(gz/self._norm, axis=1) * x
        return gx,
```

I dont get it how to calculate a gradient of np.divide?
P.s.: read xp as np (numpy)

As i understand this code wont use implemented autograd.numpy.divide, so i should not count it in:
```
>>> grad_tanh = grad(tanh)       # Obtain its gradient function
>>> grad_tanh(1.0)               # Evaluate the gradient at x = 1.0
```
ie something like
```
>>> divgrad = autograd.grad(np.divide)
```
would be overusage, no?

**Comment by mattjj** [comment]
The gradient of `np.divide` is [defined in numpy_grads.py](https://github.com/HIPS/autograd/blob/ca7ee9e27c5df3e5b2a39969c9adff7fe6ca32f8/autograd/numpy/numpy_grads.py#L73-L74):

```python
anp.divide.defgrad(lambda ans, x, y : unbroadcast(ans, x, lambda g :   g / y))
anp.divide.defgrad(lambda ans, x, y : unbroadcast(ans, y, lambda g : - g * x / y**2), argnum=1)
```

The anonymous function in the first line essentially implements the multiplication rule for ∂/∂x x/y (for computing the derivative with respect to the first argument of `divide`) and the anonymous function in the second line essentially implements the quotient rule for ∂/∂y x/y (for computing the derivative with respect to the second argument of `divide`, both in reverse mode. The [`unbroadcast` function](https://github.com/HIPS/autograd/blob/ca7ee9e27c5df3e5b2a39969c9adff7fe6ca32f8/autograd/numpy/numpy_grads.py#L392-L410) effectively undoes the broadcasting that may happen to the arguments of `np.divide`.

The `defgrad` method just attaches those anonymous functions to the wrapped `divide` object so that autograd can find them when it needs to compute the reverse-mode gradient of `divide`.

That's it for the autograd implementation. If your class is meant to implement its own reverse-mode functions and not use autograd, you probably just need the gradient definitions in those anonymous functions. 

Hope that helps you write your code!

**Comment by mattjj** [comment]
Your code design might look a bit like that of [Kayak](https://github.com/HIPS/Kayak), which was a predecessor to autograd in the HIPS group. In particular, it might be helpful to glance at the [MatElemMult](https://github.com/HIPS/Kayak/blob/b8d0eca9eb4cd17e965251dcc5ed97933e49f7d8/kayak/matrix_ops.py#L113-L156) class (since there's no `MatElemDiv` class afaict). I don't think anyone is actively maintaining Kayak but I thought it couldn't hurt as inspiration.

**Comment by Strateus** [comment]
Can you please give an example of how i can use grad of np.divide?

```
>>> x = 10.
>>> y = 4.
>>> np.divide(x, y)
2.5
>>> autograd.numpy.divide(x, y)
2.5
>>> autograd.numpy.divide.defgrad(x, y)
>>> 
```

**Comment by mattjj** [comment]
```python
import autograd.numpy as np
from autograd import grad

print grad(np.divide)(3., 2.)
print grad(np.divide, argnum=1)(3., 2.)
```

It's the same as everything else in autograd; see the README, tutorial, and examples.

**Comment by Strateus** [comment]
Thank you, thought you had a shortcut for numpy implemented functions.

**Comment by Strateus** [comment]
Hmm strange results i get with the method you proposed:

```
>>> x = np.random.random((2,3))
>>> _norm = np.linalg.norm(x, 2, 1)
>>> y = np.expand_dims(_norm, axis=1)
>>> x
array([[ 0.50578627,  0.37340201,  0.52078787],
       [ 0.96267211,  0.5459987 ,  0.18807968]])
>>> y
array([[ 0.81637542],
       [ 1.12259795]])
>>> autograd.grad(np.divide, argnum=0)(x, y)
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
>>> autograd.grad(np.divide, argnum=1)(x, y)
array([[ 0.],
       [ 0.]])
>>> dX = autograd.grad(np.divide, argnum=0)
>>> dY = autograd.grad(np.divide, argnum=1)
>>> dX(np.random.random((2,3)), np.random.random((2,1)))
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
>>> dX(np.random.random((2,3)), np.random.random((2,1)))
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
>>> dX(np.random.random((2,3)), np.random.random((2,1)))
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
>>> dY(np.random.random((2,3)), np.random.random((2,1)))
array([[ 0.],
       [ 0.]])
>>> dY(np.random.random((2,3)), np.random.random((2,1)))
array([[ 0.],
       [ 0.]])
>>> dY(np.random.random((2,3)), np.random.random((2,1)))
array([[ 0.],
       [ 0.]])
>>> 
```

Maybe im missing the point of gradient but how its possible to be zero on both inputs?

**Comment by mattjj** [comment]
It looks like you forgot to do `import autograd.numpy as np` and instead just did `import numpy as np`.

Also, the `grad` function can only differentiate scalar-valued functions, and `np.divide` applied to those arrays is not scalar-valued. You can either use `autograd.jacobian` or differentiate a scalar-valued function like this one:

```python
In [1]: from autograd import grad

In [2]: import autograd.numpy as np

In [3]: x = np.array([[ 0.50578627,  0.37340201,  0.52078787],
       [ 0.96267211,  0.5459987 ,  0.18807968]])

In [4]: y = np.array([[ 0.81637542],
       [ 1.12259795]])

In [5]: grad(lambda x, y: np.sum(np.divide(x,y)))(x, y)
Out[5]:
array([[ 1.22492664,  1.22492664,  1.22492664],
       [ 0.89079087,  0.89079087,  0.89079087]])
```

**Comment by Strateus** [comment]
Thank you, thought i could use only numpy functions to compute this grad since CuPy wont support autograd and numpy/cupy interface should be same for me ehh.
