### ISSUE TITLE
int dtype checking broken by #71

### ISSUE THREAD

**Issue by mattjj** [HIPS/autograd#81]
@gbarta reported in [sampyl #14](https://github.com/mcleonard/sampyl/issues/14) that the fix to #71 broke this kind of dtype checking against numpy's int dtypes like `np.int`:

```python
if x.dtype != np.int_:
    # ...
```

Instead of wrapping the dtype objects like `np.int` as callables, we could resolve this issue by subclassing `np.int` (and the other numpy int dtypes) and overriding `__new__`.

**Comment by gbarta** [comment]
Python2 is good, but there is still a problem in python3.

This is in the line `isinstance(x, int) or isinstance(x, np.int_)` used in sampyl.discrete_uniform.  The value is not an instance of the wrapped int_ type because it was not create by the wrapper, so it is only the first check that has an effect.  In numpy for python2, numpy.int64 has int as a base class so it returns true, but surprisingly to me in numpy for python3 this is not the case.

I am not sure what you can do about this case - it may have to be fixed in sampyl with a more robust integral check like `isinstance(x,numbers.Integral)`

**Comment by mattjj** [comment]
Hmm, interesting. In general autograd can break isinstance checks (there's a note in the tutorial about it). But this one seems like it is a numpy bug (if it is a bug); that is, autograd is correctly inheriting numpy's behavior in both Python 2 and 3, though numpy's behavior differs in the two versions. Does that sound right to you?

**Comment by gbarta** [comment]
The bit about numpy for python3 not inheriting int looks like deliberate behaviour because in python2 int is a machine integer and in python3 int is a big integer.  So that isn't a bug.

Otherwise, the isinstance(x.np.int_) problem seems similar to known issues with isinstance in autograd.  See here:

    >>> import autograd.numpy as np                                                        
    >>> type(np.int_(3))                                                                   
    <class 'autograd.numpy.numpy_wrapper.wrap_intdtype.<locals>.IntdtypeSubclass'>         
    >>> type(np.array([1])[0])                                                             
    <class 'numpy.int32'>             
    >>> type(np.array([1],dtype=np.int_)[0])
    <class 'numpy.int32'>
    >>> type(np.floor(3.14).astype(np.int_))                                               
    <class 'numpy.int32'>                                                                  

Of those 4 cases, the first is fine and the second is maybe undesirable but understandable since a type hasn't been specified.  It is unfortunate in the third and fourth cases that numpy doesn't honour the requested type.  This might be a bug, or might just be the abstraction leaking though, since numpy doesn't really hold python types internally.
