### ISSUE TITLE
Gradient of np.sum raises TypeError

### ISSUE THREAD

**Issue by dfm** [HIPS/autograd#85]
Thanks for sharing this awesome project!

Using the GitHub master of autograd and numpy v1.10.2, I tried the following simple function:

```
import autograd
import numpy as np

def function(x):
    return -0.5*np.sum(x**2)

autograd.grad(function)(np.random.randn(10))
```

but it raises the `TypeError`:

```
TypeError: make_grad_np_sum() got an unexpected keyword argument 'dtype'
```

I assume that this keyword must have been added in a recent numpy release but I can't work out exactly when. This error won't block my project (I know how to write a function like this in a way that works) but I figured I should share this issue here just in case.

Thanks again for your work on this module!

**Comment by mattjj** [comment]
You wrote `import numpy as np` but you need to write `import autograd.numpy as np`.

**Comment by mattjj** [comment]
To say a bit more, autograd works by wrapping numpy's functions so that when evaluating a gradient they do some extra bookkeeping on the side. That's why you need to replace imports like `import numpy as np` with `import autograd.numpy as np`.

It's an easy mistake to make (I did the same in #49!) and the error message is pretty opaque. I just added a hint to the error message, so that when running your test case above this prints out at the bottom of the traceback:

```
AutogradHint: This error *might* be caused by importing numpy instead of autograd.numpy, so check that you have 'import autograd.numpy as np' at the top of your file instead of 'import numpy as np'.
Sub-exception:
TypeError: make_grad_np_sum() got an unexpected keyword argument 'dtype'
```

**Comment by dfm** [comment]
Oh my that is embarrassing! Thanks for the postscript :-)
